use ods;
truncate table `dwd`.dwd_order_houses;
-- 更新信息 1 房产信息
insert  into `dwd`.dwd_order_houses(id,house_api,
house_apply_no,
house_no,
house_cert_type,
house_cert_no,
house_new_house_cert_no,
house_type,
house_area,
house_address,
house_acreage,
house_register_price,
house_register_date,
house_completion_date,
house_land_expiry,
house_land_right_no,
house_remark,
house_property_owner_info,
house_create_user_id,
house_update_user_id,
house_create_time,
house_update_time,
house_age,
house_housing_status,
house_property,
house_type_other,
house_location,
house_location_province,
house_location_city,
house_area_code,
house_interior_house_acreage,
house_borrower_equity,
house_owner_type,
house_owner_number,
house_mortgage_date,
house_mortgage_struct,
house_mortgage_type,
house_mortgage_status,
house_rent_status,
house_right_property,
house_right_type,
house_total_floor,
house_prop_buy_time,
house_project_name,
house_is_only_house,
house_fxt_area_code,
house_fxt_area_name,
house_village_name,
house_building_no,
house_floor_no,
house_room_no,
house_build_year,
house_land_type,
house_is_second_mortgage,
house_mold,
house_loan_agency_type,
house_loan_agency_name,
house_mortgage_right_amount,
house_other_estate_type,
house_comprehensive_average_price,
house_comprehensive_evaluation_price,
house_in_reserve_house)
SELECT
a.id, -- as 'id',
'house', -- as '房产信息类型',
a.apply_no, -- as '订单编号',
a.house_no, -- as '房产编号',
a.cert_type, -- as '房产证类型',
a.house_cert_no, -- as '产证编号',
a.new_house_cert_no, -- as '新房产证编号',
a.house_type, -- as '房产用途',
a.house_area, -- as '所在区域',
a.house_address, -- as '房产地址（坐落）',
a.house_acreage, -- as '房屋面积',
a.register_price, -- as '登记价（元）',
a.register_date, -- as '登记日期',
a.completion_date, -- as '竣工日期',
a.land_expiry, -- as '土地使用期限',
a.land_right_no, -- as '丘权号',
a.remark, -- as '房产信息备注',
a.property_owner_info, -- as '产权人相关信息',
a.create_user_id, -- as '房产信息创建人id',
a.update_user_id, -- as '房产信息更新人id',
a.create_time, -- as '房产信息记录创建时间',
a.update_time, -- as '房产信息记录更新时间',
a.house_age, -- as '房龄',
a.housing_status, -- as '房屋现状(对应字典表fwxz)',
a.house_property, -- as '房屋性质',
a.house_type_other, -- as '房产用途其他',
a.house_location, -- as '房产证地址（省份、直辖市、自治区  （广东省，深圳市，南山区）逗号分隔）',
a.house_location_province, -- as '省',
a.house_location_city, -- as '市',
a.house_area_code, -- as '区域编码',
a.interior_house_acreage, -- as '套内建筑面积',
a.borrower_equity, -- as '借款人产权份额',
a.owner_type, -- as '共有情况',
a.owner_number, -- as '共有产权人数',
a.mortgage_date, -- as '抵押日期',
a.mortgage_struct, -- as '抵押物房屋结构',
a.mortgage_type, -- as '抵押物房屋类型',
a.mortgage_status, -- as '抵押状态',
a.rent_status, -- as '出租情况',
a.right_property, -- as '权利性质',
a.right_type, -- as '权利类型',
a.total_floor, -- as '总层数',
a.prop_buy_time, -- as '购房日期',
a.project_name, -- as '楼盘名称',
a.is_only_house, -- as '是否唯一住房',
a.fxt_area_code, -- as '房讯通区域编码',
a.fxt_area_name, -- as '房讯通区域名称',
a.house_village_name, -- as '',
a.house_building_no, -- as '',
a.house_floor_no, -- as '楼层号',
a.house_room_no, -- as '门牌号',
a.build_year, -- as '建造时间',
a.land_type, -- as '土地类型',
a.is_second_mortgage, -- as '是否在我司二押',
a.house_mold, -- as '房产类型',
a.loan_agency_type, -- as '贷款机构类型',
a.loan_agency_name, -- as '贷款机构名称',
a.mortgage_right_amount, -- as '抵押债权金额',
a.other_estate_type, -- as '其他房产类型',
a.comprehensive_average_price, -- as '综合评估均价',
a.comprehensive_evaluation_price, -- as '综合评估总价',
a.in_reserve_house -- as '是否备用房'
from ods_bpms_biz_house a;

-- 更新信息 ２ 土地证信息
insert into `dwd`.dwd_order_houses (id,
house_api,
house_apply_no,
house_no,
house_cert_type,
house_cert_no,
house_type,
land_parcel_no,
land_useright_gain_way,
land_use,
land_remark,
land_create_user_id,
land_update_user_id,
land_create_time,
land_update_time,
land_useright_gain_way_other,
land_type_other,
land_type,
land_area_use,
land_share_area,
land_house_location,
land_end_date,
land_alone_area) SELECT b.id, -- as 'id',
'land', -- as '房产信息类型',
apply_no, -- as '订单编号',
house_no, -- as '房产编号',
'', -- as '房产证类型',
'', -- as '产证编号',
'', -- as '房产用途',
b.land_parcel_no, -- as '地号（宗地号）',
b.useright_gain_way, -- as '使用权取得方式',
b.land_use, -- as '土地用途',
b.remark, -- as '二地证备注',
b.create_user_id, -- as '创建人id',
b.update_user_id, -- as '更新人id',
b.create_time, -- as '记录创建时间',
b.update_time, -- as '记录更新时间',
b.useright_gain_way_other, -- as '使用权取得方式其他',
b.land_type_other, -- as '地类其他',
b.land_type, -- as '地类',
b.area_use, -- as '使用权面积',
b.share_area, -- as '分摊面积',
b.house_location, -- as '房屋坐落',
b.end_date, -- as '终止日期',
b.alone_area -- as '独用面积'
from ods_bpms_biz_land_cert b;


-- 更新信息 3 查评估信息
insert into `dwd`.dwd_order_houses (id,
house_api,
house_apply_no,
house_no,
house_cert_type,
house_cert_no,
house_type,
estimate_price_source,
estimate_query_time,
estimate_market_average_price,
estimate_query_user_id,
estimate_query_user_name,
estimate_remark,
estimate_create_user_id,
estimate_update_user_id,
estimate_create_time,
estimate_update_time,
estimate_rev,
`estimate_sourcetype`,
estimate_total_price,
estimate_manual_total_price,
estimate_average_price,
estimate_liveness,
estimate_average_price2,
estimate_total_price2,
estimate_comprehensive_evaluation_price,
estimate_comprehensive_average_price,
estimate_total_price3,
estimate_average_price3,
estimate_old_or_new,
estimate_system_source,
estimate_query_condition,
estimate_price,
estimate_query_way,
estimate_query_result,
estimate_unique_id) SELECT c.id, -- as 'id',
'estimate', -- as '房产信息类型',
apply_no, -- as '订单编号',
house_no, -- as '房产编号',
cert_type, -- as '房产证类型',
cert_no, -- as '产证编号',
'', -- as '房产用途',
c.price_source, -- as '价格来源',
c.query_time, -- as '查询时间',
c.market_average_price, -- as '市场均价（元）',
c.query_user_id, -- as '查询人id',
c.query_user_name, -- as '查询姓名',
c.remark, -- as '备注',
c.create_user_id, -- as '创建人id',
c.update_user_id, -- as '更新人id',
c.create_time, -- as '记录创建时间',
c.update_time, -- as '记录更新时间',
c.`rev`, -- as '版本号',
c.`sourceType`, -- as '征信来源',
c.total_price, -- as '查评估总价1',
c.manual_total_price, -- as '人工录入评估总价2',
c.average_price, -- as '查评估均价',
c.liveness, -- as '活跃度',
c.average_price2, -- as '查评估均价2',
c.total_price2, -- as '查评估总价2',
c.comprehensive_evaluation_price, -- as '综合评估价',
c.comprehensive_average_price, -- as '综合均价',
c.total_price3, -- as '云房总价',
c.average_price3, -- as '云房均价',
c.old_or_new, -- as '新老单标记',
c.system_source, -- as '系统来源',
c.query_condition, -- as '查询条件',
c.price, -- as '均价(元/m2)',
c.query_way, -- as '查询方式(线上/线下)',
c.query_result, -- as '查询结果状态',
c.unique_id --  as '查询条件'
from ods_bpms_biz_query_estimate c;

-- 更新信息 4 查档
insert into `dwd`.dwd_order_houses (id,
house_api,
house_apply_no,
house_no,
house_cert_type,
house_cert_no,
house_type,
archive_query_time,
archive_query_result,
archive_query_user_id,
archive_query_user_name,
archive_remark,
archive_create_user_id,
archive_update_user_id,
archive_create_time,
archive_update_time) SELECT d.id, -- as 'id',
'archive', -- as '房产信息类型',
apply_no, -- as '订单编号',
house_no, -- as '房产编号',
cert_type, -- as '房产证类型',
cert_no, -- as '产证编号',
'', -- as '房产用途',
d.query_time, -- as '查询时间',
d.query_result, -- as '查档结果',
d.query_user_id, -- as '查档人id',
d.query_user_name, -- as '查档人姓名',
d.remark, -- as '备注',
d.create_user_id, -- as '创建人id',
d.update_user_id, -- as '更新人id',
d.create_time, -- as '记录创建时间',
d.update_time --  as '记录更新时间'
from ods_bpms_biz_query_archive d;