set hive.execution.engine=spark;
use ods;
drop table if exists dwd.dwdtmp_order_fees;
create table if not exists dwd.dwdtmp_order_fees (
    apply_no STRING COMMENT '订单编号',
  fee_summary_product_term STRING COMMENT '产品期限',
  fee_summary_is_same_bank STRING COMMENT '是否同行',
  fee_summary_premium_summary DOUBLE COMMENT '汇总保费',
  fee_summary_premium_payment_party STRING COMMENT '保费缴纳方',
  fee_summary_remove_insurance_time STRING COMMENT '解保时间',
  fee_summary_net_income_amount DOUBLE COMMENT '大道净收入(元)',
  fee_summary_service_fee_amount DOUBLE COMMENT '大道服务费',
  fee_summary_service_payment_party STRING COMMENT '服务费缴纳方',
  fee_summary_total_amount DOUBLE COMMENT '缴费金额合计(元)',
  fee_summary_payment_way STRING COMMENT '收费方式',
  fee_summary_has_invoice STRING COMMENT '有无专票(0无1有)',
  fee_summary_price_tag STRING COMMENT '价格标签',
  fee_summary_remark STRING COMMENT '费用备注',
  fee_summary_create_user_id STRING COMMENT '创建人id',
  fee_summary_update_user_id STRING COMMENT '更新人id',
  fee_summary_create_time STRING COMMENT '记录创建时间',
  fee_summary_update_time STRING COMMENT '记录更新时间',
  fee_summary_rev bigint comment '版本号',
  fee_summary_delete_flag STRING COMMENT '记录删除标识(1删除0有效记录)',
  fee_summary_turnover_amount DOUBLE COMMENT '周转金额',
  fee_summary_borrowing_amount DOUBLE COMMENT '借款金额',
  fee_summary_ransom_borrow_amount DOUBLE COMMENT '赎楼金额',
  fee_summary_own_fund_amount DOUBLE COMMENT '卖方自有资金',
  fee_summary_refund_source STRING COMMENT '还款来源',
  fee_summary_borrowing_value_date STRING COMMENT '借款起息日',
  fee_summary_borrowing_due_date STRING COMMENT '借款到期日',
  fee_summary_platform_due_date STRING COMMENT '平台到期日',
  fee_summary_platform_value_date STRING COMMENT '平台起息日',
  fee_summary_show_due_date STRING COMMENT '展示到期日',
  fee_summary_fund_use_date_num bigint comment '资金实质使用天数',
  fee_summary_contract_rate DOUBLE COMMENT '合同费率',
  fee_summary_contract_rate_total DOUBLE COMMENT '合同费率合计',
  fee_summary_floor_price_rate DOUBLE COMMENT '底价费率',
  fee_summary_floor_price_rate_total DOUBLE COMMENT '底价费率合计',
  fee_summary_fixed_term bigint comment '固定期限',
  fee_summary_product_term_and_charge_way STRING COMMENT '产品期限及收费方式选择',
  fee_summary_rabate_rate DOUBLE COMMENT '返佣率',
  fee_summary_rate DOUBLE COMMENT '费率',
  fee_summary_approve_amount DOUBLE COMMENT '审批金额(真融宝)',
  fee_summary_pre_ransom_borrow_amount DOUBLE COMMENT '预计借款(赎楼)',
  fee_summary_pre_use_amount_date STRING COMMENT '预计用款时间',
  fee_summary_guarantee_amount DOUBLE COMMENT '保障金额(元)',
  fee_summary_down_payment_amount DOUBLE COMMENT '买方首付款金额(元)',
  fee_summary_risk_grade STRING COMMENT '风险等级',
  fee_summary_end_bearing STRING COMMENT '头尾计息(0否1是)',
  fee_summary_use_amount_date STRING COMMENT '用款时间',
  fee_summary_random_pay_mode STRING COMMENT '赎楼款支付方式',
  fee_summary_tail_pay_mode STRING COMMENT '尾款支付方式',
  fee_summary_tail_account_type STRING COMMENT '尾款收款账户类型',
  fee_summary_seller_account_type STRING COMMENT '卖方收款账户类型',
  fee_summary_tail_amount DOUBLE COMMENT '尾款金额',
  fee_summary_expect_use_time STRING COMMENT '客户预计用款时间',
  fee_summary_price_discount STRING COMMENT '定价折扣',
  fee_summary_risk_coefficient STRING COMMENT '风险系数',
  fee_summary_expect_cust_pay_day STRING COMMENT '预计借款回款日(客户)',
  cust_charge_base_yushou DOUBLE COMMENT '逾收基础收费(元)',
  cust_charge_return_commission_yushou DOUBLE COMMENT '逾收返佣(元)',
  cust_charge_append_service_charge_yushou DOUBLE COMMENT '逾收附加服务费(元)',
  cust_charge_collection_charge_yushou DOUBLE COMMENT '逾收代收费用(元)',
  cust_charge_overdue_penalty_yushou DOUBLE COMMENT '逾收过期罚款(元)',
  cust_charge_total_yushou DOUBLE COMMENT '逾收合计(上述之和)',
  cust_charge_create_user_id_yushou STRING COMMENT '逾收创建人id',
  cust_charge_update_user_id_yushou STRING COMMENT '逾收更新人id',
  cust_charge_create_time_yushou STRING COMMENT '逾收记录创建时间',
  cust_charge_update_time_yushou STRING COMMENT '逾收记录更新时间',
  cust_charge_base_yingshou DOUBLE COMMENT '应收基础收费(元)',
  cust_charge_return_commission_yingshou DOUBLE COMMENT '应收返佣(元)',
  cust_charge_append_service_charge_yingshou DOUBLE COMMENT '应收附加服务费(元)',
  cust_charge_collection_charge_yingshou DOUBLE COMMENT '应收代收费用',
  cust_charge_overdue_penalty_yingshou DOUBLE COMMENT '应收过期罚款(元)',
  cust_charge_total_yingshou DOUBLE COMMENT '应收合计(上述之和)',
  cust_charge_create_user_id_yingshou STRING COMMENT '应收创建人id',
  cust_charge_update_user_id_yingshou STRING COMMENT '应收更新人id',
  cust_charge_create_time_yingshou STRING COMMENT '应收记录创建时间',
  cust_charge_update_time_yingshou STRING COMMENT '应收记录更新时间',
  cust_charge_base_yb_tuifei DOUBLE COMMENT '应补退费基础收费(元)',
  cust_charge_return_commission_yb_tuifei DOUBLE COMMENT '应补退费返佣(元)',
  cust_charge_append_service_charge_yb_tuifei DOUBLE COMMENT '应补退费附加服务费(元)',
  cust_charge_collection_charge_yb_tuifei DOUBLE COMMENT '应补退费代收费用',
  cust_charge_overdue_penalty_yb_tuifei DOUBLE COMMENT '应补退费过期罚款(元)',
  cust_charge_total_yb_tuifei DOUBLE COMMENT '应补退费合计(上述之和)',
  cust_charge_create_user_id_yb_tuifei STRING COMMENT '应补退费创建人id',
  cust_charge_update_user_id_yb_tuifei STRING COMMENT '应补退费更新人id',
  cust_charge_create_time_yb_tuifei STRING COMMENT '应补退费记录创建时间',
  cust_charge_update_time_yb_tuifei STRING COMMENT '应补退费记录更新时间',
  cust_charge_base_sb_tuifei DOUBLE COMMENT '实补基础收费(元)',
  cust_charge_return_commission_sb_tuifei DOUBLE COMMENT '实补返佣(元)',
  cust_charge_append_service_charge_sb_tuifei DOUBLE COMMENT '实补附加服务费(元)',
  cust_charge_collection_charge_sb_tuifei DOUBLE COMMENT '实补代收费用',
  cust_charge_overdue_penalty_sb_tuifei DOUBLE COMMENT '实补过期罚款(元)',
  cust_charge_total_sb_tuifei DOUBLE COMMENT '实补合计(上述之和)',
  cust_charge_create_user_id_sb_tuifei STRING COMMENT '实补创建人id',
  cust_charge_update_user_id_sb_tuifei STRING COMMENT '实补更新人id',
  cust_charge_create_time_sb_tuifei STRING COMMENT '实补记录创建时间',
  cust_charge_update_time_sb_tuifei STRING COMMENT '实补记录更新时间',
  return_capital DOUBLE COMMENT '本金(元)',
  return_loan_interest DOUBLE COMMENT '借款利率(元)a',
  return_platform_charge DOUBLE COMMENT '平台费(元)',
  return_penalty_advanced_refund DOUBLE COMMENT '罚息_提前还款(元)',
  return_penalty_overdue DOUBLE COMMENT '罚息_逾期(元)',
  return_penalty_show_time DOUBLE COMMENT '罚息_展期(元)',
  return_create_user_id STRING COMMENT '创建人id',
  return_update_user_id STRING COMMENT '更新人id',
  return_create_time STRING COMMENT '记录创建时间',
  return_update_time STRING COMMENT '记录更新时间'
);
with bc1 as (
SELECT
apply_no,
base_charge cust_charge_base_yushou,
return_commission cust_charge_return_commission_yushou,
append_service_charge cust_charge_append_service_charge_yushou,
collection_charge cust_charge_collection_charge_yushou,
overdue_penalty cust_charge_overdue_penalty_yushou,
total cust_charge_total_yushou,
create_user_id cust_charge_create_user_id_yushou,
update_user_id cust_charge_update_user_id_yushou,
create_time cust_charge_create_time_yushou,
update_time cust_charge_update_time_yushou
FROM
ods_bpms_biz_customer_charge_info where type='yushou'),

bc2 as (
SELECT
apply_no,
base_charge cust_charge_base_yingshou,
return_commission cust_charge_return_commission_yingshou,
append_service_charge cust_charge_append_service_charge_yingshou,
collection_charge cust_charge_collection_charge_yingshou,
overdue_penalty cust_charge_overdue_penalty_yingshou,
total cust_charge_total_yingshou,
create_user_id cust_charge_create_user_id_yingshou,
update_user_id cust_charge_update_user_id_yingshou,
create_time cust_charge_create_time_yingshou,
update_time cust_charge_update_time_yingshou
FROM
ods_bpms_biz_customer_charge_info where type='yingshou'),

bc3 as (
SELECT
apply_no,
base_charge cust_charge_base_yb_tuifei,
return_commission cust_charge_return_commission_yb_tuifei,
append_service_charge cust_charge_append_service_charge_yb_tuifei,
collection_charge cust_charge_collection_charge_yb_tuifei,
overdue_penalty cust_charge_overdue_penalty_yb_tuifei,
total cust_charge_total_yb_tuifei,
create_user_id cust_charge_create_user_id_yb_tuifei,
update_user_id cust_charge_update_user_id_yb_tuifei,
create_time cust_charge_create_time_yb_tuifei,
update_time cust_charge_update_time_yb_tuifei
FROM
ods_bpms_biz_customer_charge_info where type='yingbu_tuifei'),

bc4 as (
SELECT
apply_no,
base_charge cust_charge_base_sb_tuifei,
return_commission cust_charge_return_commission_sb_tuifei,
append_service_charge cust_charge_append_service_charge_sb_tuifei,
collection_charge cust_charge_collection_charge_sb_tuifei,
overdue_penalty cust_charge_overdue_penalty_sb_tuifei,
total cust_charge_total_sb_tuifei,
create_user_id cust_charge_create_user_id_sb_tuifei,
update_user_id cust_charge_update_user_id_sb_tuifei,
create_time cust_charge_create_time_sb_tuifei,
update_time cust_charge_update_time_sb_tuifei
FROM
ods_bpms_biz_customer_charge_info where type='shibu_tuifei'),

bc as (
select bc1.apply_no,
bc1.cust_charge_base_yushou,
bc1.cust_charge_return_commission_yushou,
bc1.cust_charge_append_service_charge_yushou,
bc1.cust_charge_collection_charge_yushou,
bc1.cust_charge_overdue_penalty_yushou,
bc1.cust_charge_total_yushou,
bc1.cust_charge_create_user_id_yushou,
bc1.cust_charge_update_user_id_yushou,
bc1.cust_charge_create_time_yushou,
bc1.cust_charge_update_time_yushou,
bc2.cust_charge_base_yingshou,
bc2.cust_charge_return_commission_yingshou,
bc2.cust_charge_append_service_charge_yingshou,
bc2.cust_charge_collection_charge_yingshou,
bc2.cust_charge_overdue_penalty_yingshou,
bc2.cust_charge_total_yingshou,
bc2.cust_charge_create_user_id_yingshou,
bc2.cust_charge_update_user_id_yingshou,
bc2.cust_charge_create_time_yingshou,
bc2.cust_charge_update_time_yingshou,
bc3.cust_charge_base_yb_tuifei,
bc3.cust_charge_return_commission_yb_tuifei,
bc3.cust_charge_append_service_charge_yb_tuifei,
bc3.cust_charge_collection_charge_yb_tuifei,
bc3.cust_charge_overdue_penalty_yb_tuifei,
bc3.cust_charge_total_yb_tuifei,
bc3.cust_charge_create_user_id_yb_tuifei,
bc3.cust_charge_update_user_id_yb_tuifei,
bc3.cust_charge_create_time_yb_tuifei,
bc3.cust_charge_update_time_yb_tuifei,
bc4.cust_charge_base_sb_tuifei,
bc4.cust_charge_return_commission_sb_tuifei,
bc4.cust_charge_append_service_charge_sb_tuifei,
bc4.cust_charge_collection_charge_sb_tuifei,
bc4.cust_charge_overdue_penalty_sb_tuifei,
bc4.cust_charge_total_sb_tuifei,
bc4.cust_charge_create_user_id_sb_tuifei,
bc4.cust_charge_update_user_id_sb_tuifei,
bc4.cust_charge_create_time_sb_tuifei,
bc4.cust_charge_update_time_sb_tuifei
from ods_bpms_biz_fee_summary a left join bc1 on bc1.apply_no=a.apply_no
left join bc2 on bc2.apply_no=a.apply_no
left join bc3 on bc3.apply_no=a.apply_no
left join bc4 on bc4.apply_no=a.apply_no)


insert overwrite table dwd.`dwdtmp_order_fees` SELECT
d.apply_no apply_no,
d.product_term fee_summary_product_term,
d.is_same_bank fee_summary_is_same_bank,
d.premium_summary fee_summary_premium_summary,
d.premium_payment_party fee_summary_premium_payment_party,
d.remove_insurance_time fee_summary_remove_insurance_time,
d.net_income_amount fee_summary_net_income_amount,
d.service_fee_amount fee_summary_service_fee_amount,
d.service_payment_party fee_summary_service_payment_party,
d.total_amount fee_summary_total_amount,
d.payment_way fee_summary_payment_way,
d.has_invoice fee_summary_has_invoice,
d.price_tag fee_summary_price_tag,
d.remark fee_summary_remark,
d.create_user_id fee_summary_create_user_id,
d.update_user_id fee_summary_update_user_id,
d.create_time fee_summary_create_time,
d.update_time fee_summary_update_time,
d.rev fee_summary_rev,
d.delete_flag fee_summary_delete_flag,
d.turnover_amount fee_summary_turnover_amount,
d.borrowing_amount fee_summary_borrowing_amount,
d.ransom_borrow_amount fee_summary_ransom_borrow_amount,
d.own_fund_amount fee_summary_own_fund_amount,
d.refund_source fee_summary_refund_source,
d.borrowing_value_date fee_summary_borrowing_value_date,
d.borrowing_due_date fee_summary_borrowing_due_date,
d.platform_due_date fee_summary_platform_due_date,
d.platform_value_date fee_summary_platform_value_date,
d.show_due_date fee_summary_show_due_date,
d.fund_use_date_num fee_summary_fund_use_date_num,
d.contract_rate fee_summary_contract_rate,
d.contract_rate_total fee_summary_contract_rate_total,
d.floor_price_rate fee_summary_floor_price_rate,
d.floor_price_rate_total fee_summary_floor_price_rate_total,
d.fixed_term fee_summary_fixed_term,
d.product_term_and_charge_way fee_summary_product_term_and_charge_way,
d.rabate_rate fee_summary_rabate_rate,
d.rate fee_summary_rate,
d.approve_amount fee_summary_approve_amount,
d.pre_ransom_borrow_amount fee_summary_pre_ransom_borrow_amount,
d.pre_use_amount_date fee_summary_pre_use_amount_date,
d.guarantee_amount fee_summary_guarantee_amount,
d.down_payment_amount fee_summary_down_payment_amount,
d.risk_grade fee_summary_risk_grade,
d.end_bearing fee_summary_end_bearing,
d.use_amount_date fee_summary_use_amount_date,
d.random_pay_mode fee_summary_random_pay_mode,
d.tail_pay_mode fee_summary_tail_pay_mode,
d.tail_account_type fee_summary_tail_account_type,
d.seller_account_type fee_summary_seller_account_type,
d.tail_amount fee_summary_tail_amount,
d.expect_use_time fee_summary_expect_use_time,
d.price_discount fee_summary_price_discount,
d.risk_coefficient fee_summary_risk_coefficient,
d.expect_cust_pay_day fee_summary_expect_cust_pay_day,
bc.cust_charge_base_yushou,
bc.cust_charge_return_commission_yushou,
bc.cust_charge_append_service_charge_yushou,
bc.cust_charge_collection_charge_yushou,
bc.cust_charge_overdue_penalty_yushou,
bc.cust_charge_total_yushou,
bc.cust_charge_create_user_id_yushou,
bc.cust_charge_update_user_id_yushou,
bc.cust_charge_create_time_yushou,
bc.cust_charge_update_time_yushou,
bc.cust_charge_base_yingshou,
bc.cust_charge_return_commission_yingshou,
bc.cust_charge_append_service_charge_yingshou,
bc.cust_charge_collection_charge_yingshou,
bc.cust_charge_overdue_penalty_yingshou,
bc.cust_charge_total_yingshou,
bc.cust_charge_create_user_id_yingshou,
bc.cust_charge_update_user_id_yingshou,
bc.cust_charge_create_time_yingshou,
bc.cust_charge_update_time_yingshou,
bc.cust_charge_base_yb_tuifei,
bc.cust_charge_return_commission_yb_tuifei,
bc.cust_charge_append_service_charge_yb_tuifei,
bc.cust_charge_collection_charge_yb_tuifei,
bc.cust_charge_overdue_penalty_yb_tuifei,
bc.cust_charge_total_yb_tuifei,
bc.cust_charge_create_user_id_yb_tuifei,
bc.cust_charge_update_user_id_yb_tuifei,
bc.cust_charge_create_time_yb_tuifei,
bc.cust_charge_update_time_yb_tuifei,
bc.cust_charge_base_sb_tuifei,
bc.cust_charge_return_commission_sb_tuifei,
bc.cust_charge_append_service_charge_sb_tuifei,
bc.cust_charge_collection_charge_sb_tuifei,
bc.cust_charge_overdue_penalty_sb_tuifei,
bc.cust_charge_total_sb_tuifei,
bc.cust_charge_create_user_id_sb_tuifei,
bc.cust_charge_update_user_id_sb_tuifei,
bc.cust_charge_create_time_sb_tuifei,
bc.cust_charge_update_time_sb_tuifei,
k1.capital return_capital,
k1.loan_interest return_loan_interest,
k1.platform_charge return_platform_charge,
k1.penalty_advanced_refund return_penalty_advanced_refund,
k1.penalty_overdue return_penalty_overdue,
k1.penalty_show_time return_penalty_show_time,
k1.create_user_id return_create_user_id,
k1.update_user_id return_update_user_id,
k1.create_time return_create_time,
k1.update_time return_update_time
from ods_bpms_biz_fee_summary d LEFT JOIN ods_bpms_biz_platform_return_info k1 on k1.apply_no=d.apply_no
left join bc on bc.apply_no=d.apply_no;
drop table if exists dwd.dwd_order_fees;
ALTER TABLE dwd.dwdtmp_order_fees RENAME TO dwd.dwd_order_fees;