use dwd;
CREATE TABLE dwd.dwd_order_record_options_wx (
	product_name STRING,
	product_type STRING,
	product_version STRING,
	apply_no STRING,
	transferapply_time STRING,
	transferapply_user_id STRING,
	transferapply_user_name STRING,
	applyorder_time STRING,
	applyorder_user_id STRING,
	applyorder_user_name STRING,
	finalloan_time STRING,
	finalloan_user_id STRING,
	finalloan_user_name STRING,
	datainspection_time STRING,
	datainspection_user_id STRING,
	datainspection_user_name STRING,
	queryarchive_time STRING,
	queryarchive_user_id STRING,
	queryarchive_user_name STRING,
	houseappraisal_time STRING,
	houseappraisal_user_id STRING,
	houseappraisal_user_name STRING,
	houseinspection_time STRING,
	houseinspection_user_id STRING,
	houseinspection_user_name STRING,
	costmark_time STRING,
	costmark_user_id STRING,
	costmark_user_name STRING,
	interview_time STRING,
	interview_user_id STRING,
	interview_user_name STRING,
	costconfirm_time STRING,
	costconfirm_user_id STRING,
	costconfirm_user_name STRING,
	inputinfo_time STRING,
	inputinfo_user_id STRING,
	inputinfo_user_name STRING,
	applyloan_time STRING,
	applyloan_user_id STRING,
	applyloan_user_name STRING,
	transferout_time STRING,
	transferout_user_id STRING,
	transferout_user_name STRING,
	transferin_time STRING,
	transferin_user_id STRING,
	transferin_user_name STRING,
	agreeloanmark_time STRING,
	agreeloanmark_user_id STRING,
	agreeloanmark_user_name STRING,
	mortgagepass_time STRING,
	mortgagepass_user_id STRING,
	mortgagepass_user_name STRING,
	mortgageout_time STRING,
	mortgageout_user_id STRING,
	mortgageout_user_name STRING,
	transfermark_time STRING,
	transfermark_user_id STRING,
	transfermark_user_name STRING,
	prefile_time STRING,
	prefile_user_id STRING,
	prefile_user_name STRING,
	trustaccount_time STRING,
	trustaccount_user_id STRING,
	trustaccount_user_name STRING,
	accounttest_time STRING,
	accounttest_user_id STRING,
	accounttest_user_name STRING,
	prerandom_time STRING,
	prerandom_user_id STRING,
	prerandom_user_name STRING,
	notarization_time STRING,
	notarization_user_id STRING,
	notarization_user_name STRING,
	costitemmark_time STRING,
	costitemmark_user_id STRING,
	costitemmark_user_name STRING,
	applycheck_time STRING,
	applycheck_user_id STRING,
	applycheck_user_name STRING,
	checkmarpush_time STRING,
	checkmarpush_user_id STRING,
	checkmarpush_user_name STRING,
	mancheck_time STRING,
	mancheck_user_id STRING,
	mancheck_user_name STRING,
	checkmarsend_time STRING,
	checkmarsend_user_id STRING,
	checkmarsend_user_name STRING,
	fundsarrival_time STRING,
	fundsarrival_user_id STRING,
	fundsarrival_user_name STRING,
	checkresensure_time STRING,
	checkresensure_user_id STRING,
	checkresensure_user_name STRING,
	pushloancommand_time STRING,
	pushloancommand_user_id STRING,
	pushloancommand_user_name STRING,
	platformarrival_time STRING,
	platformarrival_user_id STRING,
	platformarrival_user_name STRING,
	transferconfirm_time STRING,
	transferconfirm_user_id STRING,
	transferconfirm_user_name STRING,
	randommark_time STRING,
	randommark_user_id STRING,
	randommark_user_name STRING,
	randomcashback_time STRING,
	randomcashback_user_id STRING,
	randomcashback_user_name STRING,
	paymentarrival_time STRING,
	paymentarrival_user_id STRING,
	paymentarrival_user_name STRING,
	sendloancommand_time STRING,
	sendloancommand_user_id STRING,
	sendloancommand_user_name STRING,
	submitverifyapply_time STRING,
	submitverifyapply_user_id STRING,
	submitverifyapply_user_name STRING,
	flooradvance_time STRING,
	flooradvance_user_id STRING,
	flooradvance_user_name STRING,
	sendverifymaterial_time STRING,
	sendverifymaterial_user_id STRING,
	sendverifymaterial_user_name STRING,
	returnapply_time STRING,
	returnapply_user_id STRING,
	returnapply_user_name STRING,
	returnconfirm_time STRING,
	returnconfirm_user_id STRING,
	returnconfirm_user_name STRING,
	getcancelmaterial_time STRING,
	getcancelmaterial_user_id STRING,
	getcancelmaterial_user_name STRING,
	canclemortgage_time STRING,
	canclemortgage_user_id STRING,
	canclemortgage_user_name STRING,
	insuranceinfoconfirm_time STRING,
	insuranceinfoconfirm_user_id STRING,
	insuranceinfoconfirm_user_name STRING,
	sendloanrelesecommand_time STRING,
	sendloanrelesecommand_user_id STRING,
	sendloanrelesecommand_user_name STRING,
	overinsurance_time STRING,
	overinsurance_user_id STRING,
	overinsurance_user_name STRING,
	custpayment_time STRING,
	custpayment_user_id STRING,
	custpayment_user_name STRING,
	mortgagepass_zz_time STRING,
	mortgagepass_zz_user_id STRING,
	mortgagepass_zz_user_name STRING,
	mortgageout_zz_time STRING,
	mortgageout_zz_user_id STRING,
	mortgageout_zz_user_name STRING,
	canclemortgage_zz_time STRING,
	canclemortgage_zz_user_id STRING,
	canclemortgage_zz_user_name STRING,
	transferout_zz_time STRING,
	transferout_zz_user_id STRING,
	transferout_zz_user_name STRING,
	transferin_zz_time STRING,
	transferin_zz_user_id STRING,
	transferin_zz_user_name STRING,
	investigate_time STRING,
	investigate_user_id STRING,
	investigate_user_name STRING,
	policyapply_time STRING,
	policyapply_user_id STRING,
	policyapply_user_name STRING,
	creditconfirm_time STRING,
	creditconfirm_user_id STRING,
	creditconfirm_user_name STRING,
	approvalresult_time STRING,
	approvalresult_user_id STRING,
	approvalresult_user_name STRING,
	inputinfocomplete_time STRING,
	inputinfocomplete_user_id STRING,
	inputinfocomplete_user_name STRING,
	pushoutcommand_time STRING,
	pushoutcommand_user_id STRING,
	pushoutcommand_user_name STRING,
	uploadimg_time STRING,
	uploadimg_user_id STRING,
	uploadimg_user_name STRING,
	confirmarrival_time STRING,
	confirmarrival_user_id STRING,
	confirmarrival_user_name STRING,
	householdapprove_time STRING,
	householdapprove_user_id STRING,
	householdapprove_user_name STRING,
	financialarchiveevent_time STRING,
	financialarchiveevent_user_id STRING,
	financialarchiveevent_user_name STRING,
	billcheck_time STRING,
	billcheck_user_id STRING,
	billcheck_user_name STRING,
	householdsurvey_time STRING,
	householdsurvey_user_id STRING,
	householdsurvey_user_name STRING,
	transfertail_time STRING,
	transfertail_user_id STRING,
	transfertail_user_name STRING,
	confirmtailarrial_time STRING,
	confirmtailarrial_user_id STRING,
	confirmtailarrial_user_name STRING,
	agreeloanmark_atone_time STRING,
	agreeloanmark_atone_user_id STRING,
	agreeloanmark_atone_user_name STRING,
	internalturnfunds_time STRING,
	internalturnfunds_user_id STRING,
	internalturnfunds_user_name STRING,
	randomreback_time STRING,
	randomreback_user_id STRING,
	randomreback_user_name STRING,
	confirmtransfertail_time STRING,
	confirmtransfertail_user_id STRING,
	confirmtransfertail_user_name STRING,
	repaymentconfirm_time STRING,
	repaymentconfirm_user_id STRING,
	repaymentconfirm_user_name STRING,
	patch_ds_time STRING,
	patch_ds_user_id STRING,
	patch_ds_user_name STRING,
	verifyinsurance_time STRING,
	verifyinsurance_user_id STRING,
	verifyinsurance_user_name STRING,
	other_time STRING,
	other_user_id STRING,
	other_user_name STRING,
	principaltransfer_time STRING,
	principaltransfer_user_id STRING,
	principaltransfer_user_name STRING,
	principaltransferconfirm_time STRING,
	principaltransferconfirm_user_id STRING,
	principaltransferconfirm_user_name STRING,
	custreceivableconfirm_time STRING,
	custreceivableconfirm_user_id STRING,
	custreceivableconfirm_user_name STRING
) STORED AS PARQUET LOCATION 'hdfs://data-dwm-prod-53:8020/user/hive/warehouse/dwd.db/dwd_order_record_options_wx'

create table if not exists dwd.dwd_order_fees(apply_no string comment '订单编号' ,
fee_summary_product_term string comment '产品期限' ,
fee_summary_is_same_bank string comment '是否同行' ,
fee_summary_premium_summary double comment '汇总保费' ,
fee_summary_premium_payment_party string comment '保费缴纳方' ,
fee_summary_remove_insurance_time string comment '解保时间' ,
fee_summary_net_income_amount double comment '大道净收入(元)' ,
fee_summary_service_fee_amount double comment '大道服务费' ,
fee_summary_service_payment_party string comment '服务费缴纳方' ,
fee_summary_total_amount double comment '缴费金额合计(元)' ,
fee_summary_payment_way string comment '收费方式' ,
fee_summary_has_invoice string comment '有无专票(0无1有)' ,
fee_summary_price_tag string comment '价格标签' ,
fee_summary_remark string comment '费用备注' ,
fee_summary_create_user_id string comment '创建人id' ,
fee_summary_update_user_id string comment '更新人id' ,
fee_summary_create_time string comment '记录创建时间' ,
fee_summary_update_time string comment '记录更新时间' ,
fee_summary_rev bigint comment '版本号' ,
fee_summary_delete_flag string comment '记录删除标识(1删除0有效记录)' ,
fee_summary_turnover_amount double comment '周转金额' ,
fee_summary_borrowing_amount double comment '借款金额' ,
fee_summary_ransom_borrow_amount double comment '赎楼金额' ,
fee_summary_own_fund_amount double comment '卖方自有资金' ,
fee_summary_refund_source string comment '还款来源' ,
fee_summary_borrowing_value_date string comment '借款起息日' ,
fee_summary_borrowing_due_date string comment '借款到期日' ,
fee_summary_platform_due_date string comment '平台到期日' ,
fee_summary_platform_value_date string comment '平台起息日' ,
fee_summary_show_due_date string comment '展示到期日' ,
fee_summary_fund_use_date_num bigint comment '资金实质使用天数' ,
fee_summary_contract_rate double comment '合同费率' ,
fee_summary_contract_rate_total double comment '合同费率合计' ,
fee_summary_floor_price_rate double comment '底价费率' ,
fee_summary_floor_price_rate_total double comment '底价费率合计' ,
fee_summary_fixed_term bigint comment '固定期限' ,
fee_summary_product_term_and_charge_way string comment '产品期限及收费方式选择' ,
fee_summary_rabate_rate double comment '返佣率' ,
fee_summary_rate double comment '费率' ,
fee_summary_approve_amount double comment '审批金额(真融宝)' ,
fee_summary_pre_ransom_borrow_amount double comment '预计借款(赎楼)' ,
fee_summary_pre_use_amount_date string comment '预计用款时间' ,
fee_summary_guarantee_amount double comment '保障金额(元)' ,
fee_summary_down_payment_amount double comment '买方首付款金额(元)' ,
fee_summary_risk_grade string comment '风险等级' ,
fee_summary_end_bearing string comment '头尾计息(0否1是)' ,
fee_summary_use_amount_date string comment '用款时间' ,
fee_summary_random_pay_mode string comment '赎楼款支付方式' ,
fee_summary_tail_pay_mode string comment '尾款支付方式' ,
fee_summary_tail_account_type string comment '尾款收款账户类型' ,
fee_summary_seller_account_type string comment '卖方收款账户类型' ,
fee_summary_tail_amount double comment '尾款金额' ,
fee_summary_expect_use_time string comment '客户预计用款时间' ,
fee_summary_price_discount string comment '定价折扣' ,
fee_summary_risk_coefficient string comment '风险系数' ,
fee_summary_expect_cust_pay_day string comment '预计借款回款日(客户)' ,
cust_charge_base_yushou double comment '逾收基础收费(元)' ,
cust_charge_return_commission_yushou double comment '逾收返佣(元)' ,
cust_charge_append_service_charge_yushou double comment '逾收附加服务费(元)' ,
cust_charge_collection_charge_yushou double comment '逾收代收费用(元)' ,
cust_charge_overdue_penalty_yushou double comment '逾收过期罚款(元)' ,
cust_charge_total_yushou double comment '逾收合计(上述之和)' ,
cust_charge_create_user_id_yushou string comment '逾收创建人id' ,
cust_charge_update_user_id_yushou string comment '逾收更新人id' ,
cust_charge_create_time_yushou string comment '逾收记录创建时间' ,
cust_charge_update_time_yushou string comment '逾收记录更新时间' ,
cust_charge_base_yingshou double comment '应收基础收费(元)' ,
cust_charge_return_commission_yingshou double comment '应收返佣(元)' ,
cust_charge_append_service_charge_yingshou double comment '应收附加服务费(元)' ,
cust_charge_collection_charge_yingshou double comment '应收代收费用' ,
cust_charge_overdue_penalty_yingshou double comment '应收过期罚款(元)' ,
cust_charge_total_yingshou double comment '应收合计(上述之和)' ,
cust_charge_create_user_id_yingshou string comment '应收创建人id' ,
cust_charge_update_user_id_yingshou string comment '应收更新人id' ,
cust_charge_create_time_yingshou string comment '应收记录创建时间' ,
cust_charge_update_time_yingshou string comment '应收记录更新时间' ,
cust_charge_base_yb_tuifei double comment '应补退费基础收费(元)' ,
cust_charge_return_commission_yb_tuifei double comment '应补退费返佣(元)' ,
cust_charge_append_service_charge_yb_tuifei double comment '应补退费附加服务费(元)' ,
cust_charge_collection_charge_yb_tuifei double comment '应补退费代收费用' ,
cust_charge_overdue_penalty_yb_tuifei double comment '应补退费过期罚款(元)' ,
cust_charge_total_yb_tuifei double comment '应补退费合计(上述之和)' ,
cust_charge_create_user_id_yb_tuifei string comment '应补退费创建人id' ,
cust_charge_update_user_id_yb_tuifei string comment '应补退费更新人id' ,
cust_charge_create_time_yb_tuifei string comment '应补退费记录创建时间' ,
cust_charge_update_time_yb_tuifei string comment '应补退费记录更新时间' ,
cust_charge_base_sb_tuifei double comment '实补基础收费(元)' ,
cust_charge_return_commission_sb_tuifei double comment '实补返佣(元)' ,
cust_charge_append_service_charge_sb_tuifei double comment '实补附加服务费(元)' ,
cust_charge_collection_charge_sb_tuifei double comment '实补代收费用' ,
cust_charge_overdue_penalty_sb_tuifei double comment '实补过期罚款(元)' ,
cust_charge_total_sb_tuifei double comment '实补合计(上述之和)' ,
cust_charge_create_user_id_sb_tuifei string comment '实补创建人id' ,
cust_charge_update_user_id_sb_tuifei string comment '实补更新人id' ,
cust_charge_create_time_sb_tuifei string comment '实补记录创建时间' ,
cust_charge_update_time_sb_tuifei string comment '实补记录更新时间' ,
return_capital double comment '本金(元)' ,
return_loan_interest double comment '借款利率(元)' ,
return_platform_charge double comment '平台费(元)' ,
return_penalty_advanced_refund double comment '罚息_提前还款(元)' ,
return_penalty_overdue double comment '罚息_逾期(元)' ,
return_penalty_show_time double comment '罚息_展期(元)' ,
return_create_user_id string comment '创建人id' ,
return_update_user_id string comment '更新人id' ,
return_create_time string comment '记录创建时间' ,
return_update_time string comment '记录更新时间'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_dwd_order_fees';


create table if not exists dwd.dwd_order_record_options(record_id string comment '事项id' ,
record_apply_no string comment '订单编号' ,
record_house_no string comment '事项房产编号' ,
record_create_user_id string comment '事项创建人id' ,
record_update_user_id string comment '事项更新人id' ,
record_rev bigint comment '事项版本号' ,
record_matter_key string comment '事项的key' ,
record_matter_name string comment '事项的名字' ,
proc_task_key_ string comment '流程任务定义kEY' ,
proc_task_name_ string comment '流程任务名称' ,
record_relate_type string comment '事项关联类型' ,
record_relate_id string comment '事项任务关联流程ID' ,
record_status_ string comment '事项任务状态' ,
record_read_ string comment '事项是否已读 0未读1已读' ,
record_create_time string comment '事项创建时间' ,
record_handle_time string comment '事项处理时间' ,
record_handle_user_id string comment '事项处理人' ,
record_handle_user_name string comment '事项处理人名字' ,
proc_qualfieds_ string comment '流程有审批资格用户id串' ,
proc_qualfied_names_ string comment '流程有审批资格用户名称串' ,
proc_auditor_ string comment '流程执行人id' ,
proc_auditor_name_ string comment '流程执行人名' ,
proc_opinion_ string comment '流程审批意见' ,
proc_status_ string comment '流程审批状态。START-发起流程AWAITING_CHECK-待审批AGREE-同意AGAINST-反对RETURN-驳回ABANDON-弃权RETRIEVE-追回' ,
record_assignee_id_ string comment '事项捞单人' ,
record_accept_time string comment '事项到达时间' ,
record_due_time string comment '事项到期时间' ,
record_remark string comment '事项任务备注' ,
record_data_ string comment '事项数据' ,
record_from_key string comment '事项表单来源的key(事项产生器的key)' ,
record_from_name string comment '事项表单来源的名字' ,
record_operator_location string comment '事项操作者经纬度' ,
record_operator_address string comment '事项操作人所在地址' ,
record_operator_device string comment '事项处理设备 例如Computer Tablet' ,
record_next_matter_key string comment '事项下一办理事项' ,
record_next_handle_time string comment '事项下一事项办理时间' ,
record_node_remark string comment '事项备注信息' ,
proc_id_ string comment '意见id' ,
proc_def_id_ string comment '流程定义id' ,
proc_sup_inst_id_ string comment '父流程实例id' ,
proc_inst_id_ string comment '流程实例id' ,
proc_task_id_ string comment '流程任务id' ,
proc_token_ string comment '流程任务令牌' ,
proc_form_def_id_ string comment '流程表单定义id' ,
proc_form_name_ string comment '流程表单名' ,
proc_create_time_ string comment '流程执行开始时间' ,
proc_assign_time_ string comment '流程任务分配用户时间' ,
proc_complete_time_ string comment '流程结束时间' ,
proc_dur_ms_ bigint comment '流程持续时间(MS)' ,
proc_files_ string comment '附件' ,
proc_interpose_ bigint comment '是否干预' ,
proc_support_mobile_ string comment '支持手机端'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_dwd_order_record_options';
create table if not exists dwd.dwd_orders(apply_no string comment '订单编号' ,
create_time string comment '订单创建时间' ,
update_time string comment '订单更新时间' ,
apply_time string comment '订单申请时间' ,
house_no string comment '房产信息编号关联房产信息' ,
product_id string comment '产品ID' ,
product_name string comment '产品名字' ,
service_type string comment '业务类型(加盟商业务JMS)' ,
partner_bank_id string comment '合作银行id' ,
partner_bank_name string comment '合作银行名称' ,
partner_insurance_id string comment '合作保险公司id' ,
partner_insurance_name string comment '合作保险公司名称' ,
new_loan_bank_name string comment '新贷款银行名称' ,
new_loan_bank_code string comment '新贷款银行编号' ,
city_no string comment '城市编码' ,
city_name string comment '城市名称' ,
channel string comment '录单渠道' ,
sales_user_id string comment '渠道经理用户ID' ,
sales_user_name string comment '渠道经理姓名' ,
branch_id string comment '大道分公司编号' ,
branch_name string comment '大道分公司名' ,
sales_branch_id string comment '市场部机构编号' ,
flow_instance_id string comment '流程实例id' ,
apply_status string comment '订单状态' ,
order_create_user_id string comment '订单创建人id' ,
order_create_username string comment '订单创建人名' ,
order_update_user_id string comment '订单更新人id' ,
order_update_username string comment '订单更新人' ,
seller_user string comment '卖家姓名' ,
seller_phone string comment '卖家电话' ,
order_seller_card_no string comment '卖方身份证号' ,
seller_card_type string comment '证件类型' ,
buyer_name string comment '买家姓名' ,
buyer_phone string comment '买家电话' ,
order_emark string comment '订单备注' ,
thirdparty_name string comment '第三方公司名字' ,
thirdparty_no string comment '第三方申请编号' ,
preliminary_result string comment '预审结果' ,
follow_up_userid string comment '跟进人员ID' ,
follow_up_username string comment '跟进人员名称' ,
relate_type string comment '订单关联生成关系' ,
relate_apply_no string comment '关联的订单号' ,
group_apply_no string comment '关联在一起的订单同属一个分组' ,
man_check_first string comment '是否先审批(Y先审批后面签N先面签后审批)' ,
project_tag string comment '项目标识' ,
rob_user_id string comment '抢单用户id' ,
rob_time string comment '抢单时间' ,
rob_user_name string comment '抢单用户名称' ,
green_channel string comment '绿色通道(0不是1是)' ,
matter_sort bigint comment '事项排序字段' ,
query_part_type string comment '查询阶段类型0待面签1待放款2已放款' ,
version string comment '流程版本号' ,
matter_version bigint comment '事项的流程版本' ,
fee_summary_is_same_bank string comment '是否同行' ,
fee_summary_premium_summary double comment '汇总保费' ,
fee_summary_premium_payment_party string comment '保费缴纳方' ,
fee_summary_remove_insurance_time string comment '解保时间' ,
fee_summary_net_income_amount double comment '大道净收入(元)' ,
fee_summary_service_fee_amount double comment '大道服务费' ,
fee_summary_service_payment_party string comment '服务费缴纳方' ,
fee_summary_total_amount double comment '缴费金额合计(元)' ,
fee_summary_payment_way string comment '收费方式' ,
fee_summary_has_invoice string comment '有无专票(0无1有)' ,
fee_summary_price_tag string comment '价格标签' ,
fee_summary_remark string comment '产品费用备注' ,
fee_summary_create_user_id string comment '创建人id' ,
fee_summary_create_username string comment '产品费用创建人' ,
fee_summary_update_user_id string comment '更新人id' ,
fee_summary_update_username string comment '产品费用更新人' ,
fee_summary_turnover_amount double comment '周转金额' ,
fee_summary_borrowing_amount double comment '借款金额' ,
fee_summary_ransom_borrow_amount double comment '赎楼金额' ,
fee_summary_own_fund_amount double comment '卖方自有资金' ,
fee_summary_refund_source string comment '还款来源' ,
fee_summary_borrowing_value_date string comment '借款起息日' ,
fee_summary_borrowing_due_date string comment '借款到期日' ,
fee_summary_platform_due_date string comment '平台到期日' ,
fee_summary_platform_value_date string comment '平台起息日' ,
fee_summary_show_due_date string comment '展示到期日' ,
fee_summary_fund_use_date_num bigint comment '资金实质使用天数' ,
fee_summary_contract_rate double comment '合同费率' ,
fee_summary_contract_rate_total double comment '合同费率合计' ,
fee_summary_floor_price_rate double comment '底价费率' ,
fee_summary_floor_price_rate_total double comment '底价费率合计' ,
fee_summary_fixed_term bigint comment '固定期限' ,
fee_summary_product_term_and_charge_way string comment '产品期限及收费方式选择' ,
fee_summary_rabate_rate double comment '返佣率' ,
fee_summary_rate double comment '费率' ,
fee_summary_approve_amount double comment '审批金额(真融宝)' ,
fee_summary_pre_ransom_borrow_amount double comment '预计借款(赎楼)' ,
fee_summary_pre_use_amount_date string comment '预计用款时间' ,
fee_summary_guarantee_amount double comment '保障金额(元)' ,
fee_summary_down_payment_amount double comment '买方首付款金额(元)' ,
fee_summary_risk_grade string comment '风险等级' ,
fee_summary_end_bearing string comment '头尾计息(0否1是)' ,
fee_summary_use_amount_date string comment '用款时间' ,
fee_summary_random_pay_mode string comment '赎楼款支付方式' ,
fee_summary_tail_pay_mode string comment '尾款支付方式' ,
fee_summary_tail_account_type string comment '尾款收款账户类型' ,
fee_summary_seller_account_type string comment '卖方收款账户类型' ,
fee_summary_tail_amount double comment '尾款金额' ,
fee_summary_expect_use_time string comment '客户预计用款时间' ,
fee_summary_price_discount string comment '定价折扣' ,
fee_summary_risk_coefficient string comment '风险系数' ,
fee_summary_expect_cust_pay_day string comment '预计借款回款日(客户)' ,
fee_summary_product_term string comment '产品期限' ,
house_area string comment '所在区域' ,
house_address string comment '房产地址(坐落)' ,
is_loan_flag string comment '有无原贷款信息标识有Y没N' ,
ori_loan_bank_name string comment '原贷款银行名称' ,
ori_loan_bank_code string comment '原贷款银行编号' ,
ori_repay_method string comment '还款扣款方式预存自动扣款AUT柜台办理即时扣款DSK柜台办理系统批量扣款BAT' ,
busi_deduct_principal_balance double comment '商贷本金余额(元)' ,
pre_fine_amount double comment '预计罚息(元)' ,
deduct_date_interval string comment '扣款时间段' ,
ori_bank_user string comment '银行联系人' ,
ori_bank_phone string comment '联系方式' ,
glk_bank_name string comment '供楼卡开户行名称' ,
glk_bank_code string comment '供楼卡开户行编号' ,
glk_account_user_name string comment '供楼卡户名' ,
glk_account_user_no string comment '供楼卡户主编号' ,
glk_account_no string comment '供楼卡卡号' ,
fund_loan_flag string comment '是否有公积金贷款标识有Y没N' ,
fund_deduct_balance double comment '公积金贷款本金余额(元)' ,
fund_repay_user string comment '公积金还款联系人' ,
fund_repay_user_phone string comment '公积金还款联系人联系电话' ,
pre_ransom_date string comment '预计赎楼时间' ,
loan_remark string comment '原贷款备注' ,
first_mortgage_amount double comment '一押本金余额(元)' ,
has_second_mortgage string comment '是否为二押(Y是N否)' ,
is_prestore string comment '是否预存' ,
prestore_day string comment '预存天数' ,
ransom_repayment_start_date timestamp comment '赎楼还款开始日期' ,
ransom_repayment_end_date timestamp comment '赎楼还款结束日期' ,
is_relation_loan string comment '是否有关联贷款Y是N否' ,
loan_balance_total double comment '贷款余额合计(元)商贷余额+公积金贷款余额+关联贷款余额' ,
relation_loan_balance double comment '关联贷款余额(元)' ,
pre_provident_fund_loan_amount double comment '预计公积金贷款金额' ,
amount_regulation_code string comment '资金监管协议编号' ,
ori_borrower_type string comment '原贷款借款人类型(个人公司)' ,
ori_loan_payee string comment '原贷款借款人' ,
ori_other_non_bank string comment '其他非银机构' ,
new_house_no string comment '房产信息编号关联房产信息' ,
new_bank_email string comment '银行联系邮箱' ,
new_bank_address string comment '银行地址' ,
new_bank_user string comment '银行联系人' ,
new_bank_phone string comment '联系方式' ,
new_loan_terms string comment '贷款期数' ,
new_term_unit string comment '期限单位；D天；M月；Y年' ,
new_seller_card_no string comment '借款人身份证号码' ,
new_seller_name string comment '借款人姓名' ,
new_biz_loan_amount double comment '商业贷款金额(元)' ,
new_loan_rate double comment '贷款利率' ,
new_rate_multiply double comment '利率倍数' ,
new_repay_method_loan string comment '还款方式等额本金DEBJ等额利息DELX' ,
new_is_release string comment '状态类型01-可放款' ,
new_is_regulation_flag string comment '是否有监管有Y没N' ,
new_first_regulation_bank_name string comment '首期监管款银行' ,
new_first_regulation_bank_code string comment '首期监管款银行编号' ,
new_first_regulation_bank_account string comment '首期监管款账户' ,
new_first_regulation_amount double comment '首期监管款金额(元)' ,
new_serial_no string comment '额度协议编号' ,
new_currency string comment '币种' ,
new_business_sum double comment '名义金额' ,
new_contract_no string comment '合同流水号zyb' ,
new_borrow_cont_no string comment '借款合同编号' ,
new_max_mortgage_no string comment '最高额抵押合同编号' ,
new_start_time string comment '超始日' ,
new_end_time string comment 'ENDTIME' ,
new_provident_fund_loan_amount double comment '公积金贷款金额' ,
new_have_new_loan string comment '有无新贷款信息' ,
new_is_need_mortgage string comment '是否需我司办理按揭' ,
new_is_pay_type_check string comment '新贷款是否已核实回款来源' ,
new_loan_type string comment '贷款类型(对应字典dklx)' ,
new_natural_rate_code string comment '基准利率代码' ,
new_natural_float_type string comment '利率浮动方式(对应字典llfdfs)' ,
new_provident_fund_center string comment '贷款公积金中心' ,
natural_float_value double comment '利率浮动值' ,
new_loan_customer string comment '客户经理' ,
new_loan_customer_tel string comment '客户经理联系方式' ,
new_loan_fund_center string comment '贷款公积金中心' ,
new_loan_guaranty string comment '担保方式' ,
new_fund_rate double comment '公积金贷款利率' ,
new_fund_loan_terms string comment '公积金贷款期限' ,
new_fund_term_unit string comment '公积金期限单位；D天；M月；Y年' ,
new_has_fund_supervision string comment '是否已做资金监管？(Y是N否)' ,
new_supervision_time string comment '预计监管时间' ,
new_supervision_agreement_get_time string comment '监管协议领取时间' ,
new_borrower_type string comment '新贷款借款人类型(1个人2公司)' ,
new_transfer_loan_cause string comment '转贷动机(1利率2还款方式3期限4额度)' ,
new_third_type string comment '第三方类型(个人公司)' ,
new_is_have_fund_loan string comment '是否有公积金贷款(Y是N否)' ,
new_third_payee string comment '新贷款借款人' ,
new_other_non_bank string comment '其他非银机构' ,
new_agree_loan_type string comment '同贷类型；字典AgreeLoanType' ,
new_agree_loan_source string comment '同贷来源；字典AgreeLoanSource' ,
new_agree_loan_other_remark string comment '同贷其他来源备注' ,
new_revolving_credit_flag string comment '是否循环授信贷款1表示是0表示否' ,
new_apply_withdraw_amount double comment '申请取款金额(元)' ,
channel_name string comment '渠道名称' ,
channel_type string comment '渠道类型' ,
channel_contact string comment '联络人' ,
channel_phone string comment '渠道电话' ,
channel_rebate_man string comment '返佣人' ,
channel_rebate_bank_id string comment '返佣开户行id' ,
channel_rebate_bank string comment '返佣开户行' ,
channel_rebate_card_no string comment '返佣账号' ,
channel_tag string comment '渠道标签' ,
channel_rebate_account_type string comment '返佣账户类型(对应字典项fyzhlx)' ,
channel_rebate_type string comment '返佣类型' ,
chanel_remark string comment '渠道备注' ,
channel_tag_v3 string comment '渠道标签_v3' ,
deal_no string comment '交易合同编号' ,
deal_trading_price double comment '成交价(元)' ,
deal_earnest_money double comment '交易定金(元)' ,
deal_first_payment_paid double comment '已付首付款(元)' ,
deal_first_payment_unpaid double comment '未付首付款(元)' ,
deal_handing_room_deposit double comment '交房押金(元)' ,
deal_remark string comment '交易信息备注' ,
deal_actual_trading_price double comment '实际成交价' ,
deal_create_user_id string comment '交易创建人id' ,
deal_create_username string comment '交易创建人名' ,
deal_update_user_id string comment '更新人id' ,
deal_update_username string comment '交易更新人名' ,
deal_down_payment double comment '首付款金额' ,
deal_transfer_price double comment '过户(网签)价格' ,
con_source_funds string comment '资金来源' ,
con_funds_time string comment '确认资金到账时间' ,
con_funds_cost string comment '确认资金到账金额' ,
con_plat_date string comment '确认到账平台起息日' ,
con_plat_expire string comment '确认资金到账平台到期日' ,
con_payee_acct string comment '确认资金到账收款方' ,
con_payee_acct_no string comment '确认资金到账收款卡号' ,
con_payee_acct_name string comment '确认资金到账收款户名' ,
con_funds_deal string comment '确认资金到账交易明细id' ,
con_exec_times bigint comment '确认资金到账任务执行次数' ,
con_payee_bank string comment '确认资金到账收款开户行' ,
con_plat_arrival string comment '平台款是否到账' ,
con_plat_source_funds string comment '平台款资金来源' ,
con_plat_arrival_time string comment '平台款到账时间' ,
con_plat_recei_acct_no string comment '平台收款账户' ,
con_plat_recei_acct_name string comment '平台收款账户户名' ,
con_plat_recei_bank_name string comment '平台收款账户开户行' ,
con_plat_interest_date string comment '平台起息日' ,
con_plat_rest_date string comment '平台到期日' ,
con_plat_arriva_money double comment '平台款到账金额' ,
con_plat_arrival_deal string comment '平台款到账交易明细id' ,
con_ad_pay_time string comment '赎楼前垫资回款时间' ,
con_ad_pay_cost double comment '赎楼前垫资回款金额' ,
con_ad_pay_deal string comment '赎楼前垫资回款交易明细id' ,
con_transfer_deal string comment '资金划拨申请交易明细id' ,
con_advance_cost double comment '垫资金额' ,
con_fact_pay_source string comment '实际回款来源' ,
con_loan_pay_day string comment '借款回款日' ,
con_re_arrival_deal string comment '回款到账交易明细id' ,
con_cust_pay_day string comment '客户回款日' ,
con_cust_re_source string comment '客户回款来源' ,
con_cust_exec_times bigint comment '客户回款执行次数' ,
con_cust_re_deal string comment '客户回款交易明细id' ,
con_should_re_capital double comment '应还本金(平台)' ,
con_fact_re_capital double comment '实还本金' ,
con_should_re_interest double comment '应还利息' ,
con_fact_re_interest double comment '实际还利息' ,
con_should_re_penalty double comment '应还罚息' ,
con_penalty_overdue double comment '罚息—逾期(元)' ,
con_penalty_show_time double comment '罚息—展期(元)' ,
con_penalty_advanced_refund double comment '罚息—提前还款(元)' ,
con_fact_re_penalty double comment '实还罚息' ,
con_should_plat_cost double comment '应还平台费' ,
con_fact_plat_cost double comment '实还平台费' ,
con_should_re_sum double comment '应还合计' ,
con_fact_re_sum double comment '实还合计' ,
con_re_deal string comment '归还申请交易明细id' ,
con_plat_rece_path string comment '平台回款路径' ,
con_principal_trans_id string comment '本息划拨申请交易id' ,
con_trans_flow_id string comment '划拨流程实例id' ,
con_return_flow_id string comment '归还流程实例id' ,
con_parent_flow_id string comment '父流程实例id' ,
con_cust_should_re_capital double comment '本息划应还本金' ,
con_cust_fact_re_capital double comment '本息划拨实还本金' ,
con_cust_should_re_interest double comment '本息划拨应还利息' ,
con_cust_fact_re_interest double comment '本息划拨实还利息' ,
con_cust_should_re_penalty double comment '本息划拨应还罚息' ,
con_cust_fact_re_penalty double comment '本息划拨实还罚息' ,
con_cust_should_plat_cost double comment '本息划拨应还平台费' ,
con_cust_fact_plat_cost double comment '本息划拨实还平台费' ,
con_cust_should_re_sum double comment '本息划拨应还合计' ,
con_cust_fact_re_sum double comment '本息划拨实还合计' ,
con_plat_recei_acct string comment '平台收款方' ,
con_payee_acct_last string comment '确认资金到账上一次收款方' ,
con_deal_time string comment '交易时间' ,
con_bank_number string comment '银行流水号' ,
con_count_head_tail string comment '费用算头尾方式(suanTouBuSuanWei算头不算尾suanTouSuanWei算头算尾)' ,
con_is_need_internal string comment '是否需要内部转款(资金归还场景的内部转款)' ,
con_internal_trans_id string comment '内部转款的交易id' ,
ransom_house_no string comment '赎楼房产信息编号关联房产信息' ,
ransom_is_hold_cert string comment '业主是否持证' ,
ransom_is_already_ransom string comment '是否已预约赎楼' ,
ransom_borrow_amount double comment '赎楼借款金额' ,
ransom_own_fund_amount double comment '卖方自有资金' ,
ransom_cut_amount double comment '赎楼扣款金额' ,
ransom_cut_time string comment '赎楼扣款时间' ,
ransom_loan_rate string comment '赎楼贷款利率' ,
ransom_loan_terms string comment '赎楼贷款期限(月)' ,
ransom_repay_method string comment '赎楼贷款还款方式' ,
ransom_borrow_cont_no string comment '赎楼贷款借款合同编号' ,
ransom_bank_user string comment '赎楼贷款银行联系人' ,
ransom_bank_phone string comment '赎楼贷款联系方式' ,
ransom_seller_name string comment '赎楼贷款借款人姓名' ,
ransom_seller_card_no string comment '赎楼贷款身份证号码' ,
ransom_remark string comment '赎楼备注' ,
ransom_has_ransom_floor string comment '是否有赎楼(Y/N)' ,
ransom_has_qzjzxcl string comment '是否需要取证及注销材料(Y/N)' ,
ransom_qzjzxcl_phone string comment '取注销资料电话' ,
ransom_qzjzxcl_bank string comment '取注销资料银行总行' ,
ransom_qzjzxcl_bank_code string comment '取注销资料银行总行编码' ,
ransom_qzjzxcl_branch_bank string comment '取注销资料银行分行' ,
ransom_qzjzxcl_branch_bank_code string comment '取注销资料银行分行编码' ,
ransom_predict_qzjzxcl_time string comment '预计取注销资料时间' ,
ransom_qzjzxcl_time string comment '取注销资料时间' ,
ransom_qzjzxcl_linkman string comment '取注销资料联系人' ,
ransom_flag string comment '赎楼状态' ,
ransom_fail_reason string comment '赎楼失败原因' ,
ransom_pre_ransom_next_time string comment '预计下次赎楼时间' ,
ransom_amount_back_flag string comment '赎楼资金是否划回' ,
ransom_amout_back double comment '赎楼划回金额' ,
ransom_get_cancel_material_address string comment '取注销(后)资料地点' ,
ransom_is_company_cancel string comment '是否由我司办理注销抵押(Y是N否)' ,
ransom_is_company_get_material string comment '是否由我司领取注销抵押(后)资料'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_dwd_orders';

CREATE TABLE `dwd.dwd_orders_ex`(
`product_version` string COMMENT '版本',
`apply_no` string COMMENT '业务编号',
`product_name` string COMMENT '产品名称',
`order_amount` double COMMENT '金额',
`apply_status` string COMMENT '订单状态编码',
`apply_status_name` string COMMENT '订单状态',
`relate_apply_no` string COMMENT '关联订单号',
`group_apply_no` string COMMENT '关联组订单ID',
`relate_type_new` string COMMENT '关联生成关系',
`relate_type_name` string COMMENT '关联类型',
`risk_grade` string COMMENT '风险等级',
`price_tag` string COMMENT '价格标签',
`tail_release_node` string COMMENT '放款节点',
`apply_time` string COMMENT '业务申请时间',
`org_name` string COMMENT '所属团队',
`org_leader` string COMMENT '团队长_市场主管',
`channel_name` string COMMENT '渠道名称',
`channel_type` string COMMENT '渠道类型',
`channel_tag_new` string COMMENT '渠道标签',
`sales_user_name` string COMMENT '渠道经理',
`channel_phone` string COMMENT '渠道电话',
`channel_rebate_man` string COMMENT '返佣人',
`channel_rebate_bank` string COMMENT '返佣开户行',
`channel_rebate_card_no` string COMMENT '返佣账号',
`partner_insurance_name` string COMMENT '合作机构/保险/签约机构',
`partner_bank_name` string COMMENT '合作银行',
`own_fund_amount` double COMMENT '卖方自有资金',
`random_pay_mode` string COMMENT '赎楼款支付方式',
`tail_pay_mode` string COMMENT '尾款支付方式',
`tail_account_type` string COMMENT '尾款收款账户类型',
`fixed_term` bigint comment '预估用款期限',
`seller_name` string COMMENT '卖方/借款人姓名',
`seller_id_card_no` string COMMENT '卖方/借款人证件号码',
`seller_phone` string COMMENT '卖方/借款人联系方式',
`income_type_name` string COMMENT '收入类型',
`employer` string COMMENT '工作单位',
`marital_status_name` string COMMENT '婚姻状况',
`omate_name` string COMMENT '配偶姓名',
`id_card_no` string COMMENT '配偶证件号码',
`buy_name` string COMMENT '买方姓名',
`buy_id_card_no` string COMMENT '买方证件号码',
`buy_phone` string COMMENT '买方联系方式',
`house_no` string COMMENT '房产证号',
`house_area` string COMMENT '所在区域',
`house_address` string COMMENT '房产地址',
`house_type_name` string COMMENT '房产用途',
`house_acreage` string COMMENT '面积',
`trading_price` double COMMENT '成交价_元',
`bank_premarket_price` double COMMENT '银行报备成交价_万元市场均价',
`down_payment` double COMMENT 'buy首付款金额-元',
`earnest_money` double COMMENT 'buy交易定金-元',
`market_average_price` double COMMENT '评估价_元',
`houseappraisal_user_name` string COMMENT '评估经办人(事项)',
`update_time` string COMMENT '资质查询时间',
`audit_user_name` string COMMENT '资质查询经办人',
`archive_query_time` string COMMENT '查档时间',
`archive_user_name` string COMMENT '查档经办人事项',
`credit_query_time` string COMMENT '征信查询时间',
`credit_user_name` string COMMENT '查征信经办人',
`business_query_time` string COMMENT '工商信息查询时间',
`business_user_name` string COMMENT '工商信息查询经办人',
`litigation_query_time` string COMMENT '个人诉讼查询时间',
`litigation_user_name` string COMMENT '个人诉讼查询经办人',
`pre_business_sum` double COMMENT '预计借款(赎楼)金额',
`pre_ransom_borrow_amount` double COMMENT '预计(赎楼）贷款金额',
`guarantee_amount` double COMMENT '预计保险金额_元',
`interview_save_time` string COMMENT '面签保存时间(外勤事项)',
`ori_loan_bank_name` string COMMENT '原贷款银行',
`interview_time` string COMMENT '面签时间(外勤事项)',
`interview_user_name` string COMMENT '面签人员(外勤事项)',
`notarization_time` string COMMENT '公证时间(外勤事项)',
`notarization_user_name` string COMMENT '公证人员(外勤事项)',
`pre_ransom_date` string COMMENT '预计赎楼时间',
`repay_method_name` string COMMENT '预计赎楼扣款方式',
`busi_deduct_principal_balance` double COMMENT '商贷本金余额_元',
`fund_deduct_balance` double COMMENT '公积金贷款本金余额_',
`relation_loan_balance` double COMMENT '关联贷款余额_元',
`pre_fine_amount` double COMMENT '提前预计罚息_元',
`prerandom_time` string COMMENT '预约还款办理时间',
`prerandom_user_name` string COMMENT '预约还款经办人',
`glk_account_no` string COMMENT '赎楼还款账号',
`is_prestore` string COMMENT '是否预存(赎楼账号是否有钱)',
`prestore_day` string COMMENT '预存天数',
`applyloan_atone_time` string COMMENT '赎楼贷款申请时间ApplyLoan_atone(事项)',
`applyloan_atone_user_name` string COMMENT '赎楼贷款申请经办人ApplyLoan_atone(事项)',
`new_loan_bank_name` string COMMENT '新贷款银行',
`new_loan_type` string COMMENT '贷款类型(公积金or商贷)',
`business_sum` double COMMENT '预计商业贷款金额_元',
`biz_loan_amount_apply` double COMMENT '申请商贷金额_万元',
`provident_fund_loan_amount_apply` double COMMENT '申请公积金金额_万元',
`new_bank_user` string COMMENT '银行客户经理',
`is_regulation_flag` string COMMENT '钱是否有监管',
`pre_first_regulation_amount` double COMMENT '监管金额_元',
`supervision_organization` string COMMENT '资金监管机构',
`organization_account_agree_no` string COMMENT '资金监管协议编号',
`organization_applyloan_time` string COMMENT '资金监管经办时间',
`organization_user_name` string COMMENT '资金监管经办人',
`first_regulation_bank_name` string COMMENT '首期监管款银行',
`first_regulation_bank_code` string COMMENT '首期监管款银行编号',
`first_regulation_bank_account` string COMMENT '首期监管款账户',
`first_regulation_amount` double COMMENT '首期监管款金额(元）',
`applyloan_time` string COMMENT '按揭申请时间(新贷款)appApplyLoan',
`applyloan_user_name` string COMMENT '按揭申请经办人(新贷款)ApplyLoan',
`refund_source` string COMMENT '平台回款来源',
`fact_bu` double COMMENT '实际商业贷款金额',
`provident_fund_loan_amount` double COMMENT '实际公积金贷款金额',
`account_name` string COMMENT '平台回款卡户名',
`agreeloanmark_time` string COMMENT '核实同贷时间(外勤)',
`agreeloanmark_user_name` string COMMENT '核实同贷经办人(外勤)',
`ransom_bank_name` string COMMENT '赎楼贷款银行',
`ransom_borrow_amount` double COMMENT '实际赎楼贷款金额',
`inputinfo_time` string COMMENT '录入时间InputInfo',
`inputinfo_user_name` string COMMENT '录入人员InputInfo',
`applycheck_time` string COMMENT '报单时间(自动)ApplyCheck',
`applycheck_user_name` string COMMENT '报单人员(自动)ApplyCheck',
`investigate_time` string COMMENT '审批时间(风控)',
`status_name_` string COMMENT '审批结果(风控)',
`investigate_user_name` string COMMENT '审批人员(风控)',
`order_amount_approve` double COMMENT '审批金额_元(借款金额)',
`trustaccount_time` string COMMENT '账户托管时间(证件)TrustAccount',
`is_close_flag` string COMMENT '是否关闭网银(托管银卡)',
`trustaccount_user_name` string COMMENT '账户托管经办人(外勤)',
`costitemmark_time` string COMMENT '费项登记时间(渠道经理)',
`costitemmark_user_name` string COMMENT '费项登记人(渠道经理)',
`costconfirm_time` string COMMENT '缴费确认时间(资金岗)',
`costconfirm_user_name` string COMMENT '缴费确认人(资金岗)',
`totalreceivablefee_fee_value` double COMMENT '总收费金额_元(应收）',
`arrival_amount` double COMMENT '总收费金额_元(实收）',
`rakebackfee_fee_value` double COMMENT '代收费用合计(渠道增值)',
`substitutefeecount_fee_value` double COMMENT '返佣费',
`user_name` string COMMENT '缴费录入经办人(资金岗)',
`trans_day` string COMMENT '缴费录入时间(资金岗)',
`pushoutcommand_time` string COMMENT '外传指令推送经办时间(分公司申请发给总部)',
`pushoutcommand_user_name` string COMMENT '外传指令推送经办人(分公司申请发给总部)',
`sendverifymaterial_time` string COMMENT '核保资料外传时间(总公司确认发给机构)',
`sendverifymaterial_user_name` string COMMENT '核保资料外传经办人',
`underwrite_pass_time` string COMMENT '核保完成时间',
`policyapply_time` string COMMENT '出保单申请经办人',
`policyapply_user_name` string COMMENT '出保单申请经办时间',
`receive_policy_time` string COMMENT '接收保单时间',
`policy_no` string COMMENT '保单号码',
`loan_amount` string COMMENT '保险金额',
`premium_amount` string COMMENT '保费金额',
`premium_payment_time` string COMMENT '保费缴纳日期',
`policy_start` string COMMENT '保险起期',
`policy_end` string COMMENT '保险止期',
`insuranceinfoconfirm_time` string COMMENT '保单确认经办人InsuranceInfoConfirm',
`pushloancommand_time` string COMMENT '放款指令推送时间(分公司申请发给总部)PushLoanCommand',
`pushloancommand_user_name` string COMMENT '放款指令推送经办人(分公司申请发给总部)',
`archive_query_time_2` string COMMENT '放款前二次查档时间',
`archive_user_name_2` string COMMENT '放款前二次查档经办人',
`litigation_query_time_one_2` string COMMENT '放款前查询时间_二次查个人诉讼查询(单篇）',
`litigation_user_name_one_2` string COMMENT '放款前个人诉讼查询经办人_二次查个人诉讼查询(单篇）',
`litigation_query_time_all_2` string COMMENT '放款前查询时间_二次查个人诉讼查询(全文）',
`litigation_user_name_all_2` string COMMENT '放款前个人诉讼查询经办人_二次查个人诉讼查询(全文）',
`test_time` string COMMENT '出款前账户测试时间网银',
`test_user_name` string COMMENT '出款前账户测试人员网银',
`sendloancommand_time` string COMMENT '发送放款指令时间(总公司确认发给机构)SendLoanCommand',
`sendloancommand_user_name` string COMMENT '发送放款指令经办人(总公司确认发给机构)',
`random_fin_date` string COMMENT '赎楼前垫资时间(机构暂时打不出钱)',
`random_apply_amt` double COMMENT '赎楼前垫资金额',
`source_funds` string COMMENT '赎楼资金来源',
`con_funds_time` string COMMENT '平台资金到账时间(机构给总部或借款人)',
`loan` double COMMENT '平台到账金额_元',
`loan_terms` string COMMENT '借款期限_天',
`borrowing_value_date` string COMMENT '借款起息日(客户借款人收到钱)',
`borrowing_returned_date` timestamp,
`borrowing_carry_date` string COMMENT '借款起息日(平台机构给总部平台资金到账时间）',
`platform_due_date` string COMMENT '借款到期日(平台）',
`confirmarrival_user_name` string COMMENT '资金到账经办人(确认资金到账)',
`transferconfirm_time_apply` string COMMENT '资金划拨申请时间(机构如到公司需要划拨)资金岗',
`trans_money` double COMMENT '资金划拨申请金额',
`transferconfirm_user_name_apply` string COMMENT '资金划拨申请经办人',
`transferconfirm_time_confirm` string COMMENT '资金划拨确认时间账务岗',
`arrival_fund` double COMMENT '资金划拨确认金额',
`transferconfirm_user_name_confirm` string COMMENT '资金划拨确认经办人',
`transferconfirm_time` string COMMENT '赎楼资金划转时间外勤岗',
`transferconfirm_ransom_cut_amount` double COMMENT '赎楼资金划转金额_元',
`transferconfirm_user_name` string COMMENT '赎楼资金划转人员外勤岗',
`ransom_flag` string COMMENT '赎楼状态成没成功',
`ransom_cut_time` string COMMENT '赎楼扣款时间',
`ransom_cut_amount` double COMMENT '赎楼扣款金额',
`ransom_fail_reason` string COMMENT '赎楼失败原因',
`pre_ransom_next_time` string COMMENT '预计下次赎楼时间',
`obtain_cert_expect_time` string COMMENT '预计取证时间赎楼完什么给房产证',
`randommark_user_name` string COMMENT '赎楼扣款经办人RandomMark',
`ransom_amount_back_flag` string COMMENT '是否划回赎楼资金失败',
`ransom_amout_back` double COMMENT '划回金额失败',
`payee` string COMMENT '划回收款方(公司账号)失败',
`repay_name_back` string COMMENT '划回卡户名',
`repay_number_back` string COMMENT '划回卡帐号',
`getcancelmaterial_time` string COMMENT '领取注销资料时间外勤',
`getcancelmaterial_user_name` string COMMENT '领取注销资料经办人外勤',
`canclemortgage_time` string COMMENT '注销抵押办理时间外勤',
`canclemortgage_user_name` string COMMENT '注销抵押经办人外勤',
`canclemortgage_zz_time` string COMMENT '注销抵押_郑州_办理时间外勤',
`canclemortgage_zz_user_name` string COMMENT '注销抵押_郑州_经办人外勤',
`transferin_time` string COMMENT '过户递件时间外勤',
`transferin_zz_time` string COMMENT '过户_郑州_递件时间外勤',
`transferout_time_pre` string COMMENT '预计过户出件时间外勤',
`transferin_user_name` string COMMENT '过户递件经办人外勤',
`transferin_zz_user_name` string COMMENT '过户_郑州_递件经办人外勤',
`transferout_time` string COMMENT '过户出件时间外勤',
`transferout_user_name` string COMMENT '过户出件经办人外勤',
`sendloanrelesecommand_time` string COMMENT '发送款项释放指令时间外勤',
`bank_tail_loan_amount` double COMMENT '款项释放金额-元',
`sendloanrelesecommand_user_name` string COMMENT '发送款项释放指令经办人',
`mortgagepass_time` string COMMENT '抵押递件时间',
`mortgagepass_zz_time` string COMMENT '抵押_郑州_递件时间',
`mortgageout_time_pre` string COMMENT '预计抵押出件时间',
`mortgagepass_user_name` string COMMENT '抵押递件办理人员',
`mortgagepass_zz_user_name` string COMMENT '抵押_郑州_递件经办人',
`mortgageout_time` string COMMENT '抵押出件时间',
`mortgageout_user_name` string COMMENT '抵押出件经办人',
`mortgageout_zz_time` string COMMENT '抵押_郑州_出件时间',
`mortgageout_zz_user_name` string COMMENT '抵押_郑州_出件经办人',
`overinsurance_time` string COMMENT 'OverInsurance_time',
`overinsurance_user_name` string COMMENT '解保经办人',
`ad_pay_time` string COMMENT '赎楼前垫资回款时间',
`ad_pay_cost` double COMMENT '赎楼前垫资回款金额',
`fin_date` string COMMENT '逾期垫资时间',
`apply_amt` double COMMENT '逾期垫资金额',
`funded_repayment_time` string COMMENT '逾期垫资还款时间',
`funded_repayment_amount` double COMMENT '逾期垫资还款金额',
`fact_pay_source` string COMMENT '实际回款来源',
`paymentarrival_user_name` string COMMENT '回款资金到账经办人',
`returnapply_time` string COMMENT '资金归还申请时间',
`returnapply_user_name` string COMMENT '资金归还申请经办人',
`payment_way` string COMMENT '回款方式',
`return_funded_time` string COMMENT '归还平台借款时间',
`fact_re_capital` double COMMENT '还款金额',
`financialarchiveevent_time` string COMMENT '财务归档时间',
`financialarchiveevent_user_name` string COMMENT '财务归档经办人',
`prefile_time` string COMMENT '归档时间',
`prefile_user_name` string COMMENT '归档经办人',
`rev` bigint comment '系统版本号',
`refused_options` string COMMENT '退单原因')
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_orders_ex';

create table if not exists dwd.dwd_order_credit_risks(id string comment '主键id' ,
apply_no string comment '订单编号' ,
customer_no string comment '客户编号' ,
customer_name string comment '客户姓名' ,
credit_type string comment '征信类型' ,
parse_time string comment '解析时间' ,
parse_ret_time string comment '解析完成时间' ,
credit_channel string comment '征信获取方式' ,
report_no string comment '征信报告编号' ,
report_from string comment '征信报告来源' ,
parse_way string comment '解析方式' ,
credit_status string comment '征信状态' ,
task_id string comment '唯一任务标识(半刻查询结果使用)' ,
cache_flag string comment '是否走了缓存，未向机构发起解析请求(Y：本次解析走缓存N:本次解析未走缓存)' ,
operate_user_id string comment '操作人员id' ,
operate_user_name string comment '操作人员姓名' ,
manual_credit_query_date string comment '征信查询日期' ,
manual_credit_name string comment '姓名' ,
manual_is_sensitive_career string comment '是否为敏感职业' ,
manual_cert_type string comment '证件类型' ,
manual_cert_no string comment '证件号码' ,
manual_query_times_month3 bigint comment '近3月查询次数' ,
manual_query_times_month12 bigint comment '近12月查询次数' ,
manual_m2_overdue_has string comment '近3月有无M2以上逾期' ,
manual_m2_overdue_name string comment '近3月M2以上逾期信贷名称' ,
manual_m4_overdue_has string comment '近12月有无M4以上逾期' ,
manual_m4_overdue_name string comment '近12月M4以上逾期信贷名称' ,
manual_month12_overdue_time bigint comment '近12月逾期次数' ,
manual_month12_overdue_name string comment '近12月逾期信贷名称' ,
manual_month6_overdue_time bigint comment '近6月逾期次数' ,
manual_month6_overdue_name string comment '近6月逾期信贷名称' ,
manual_dgz_has string comment '近24月有无“D/G/Z”' ,
manual_dgz_name string comment '近24月“D/G/Z”信贷名称' ,
manual_loan_status_json string comment '贷款状态列表JSON：贷款名称，贷款账户状态，五级分类情况' ,
manual_loan_end_date_json string comment '贷款到期列表JSON：贷款名称，到期日，本金余额' ,
manual_account_info_json string comment '准/贷记卡账户信息列表JSON：名称，账户状态，当前预期次数' ,
manual_guarantee_info_json string comment '担保信息列表JSON：编号，本金余额，五级分类' ,
manual_new_loan_has string comment '有无新增无抵/质押贷款' ,
manual_new_loan_count bigint comment '新增无抵/质押贷款合计笔数' ,
manual_new_loan_amount double comment '新增无抵/质押贷款合计金额' ,
manual_card_use_amount double comment '（准）贷记卡使用金额' ,
manual_card_credit_line double comment '（准）贷记卡总授信金额' ,
manual_overdraft70_percent double comment '是否超过70百分比' ,
manual_credit_total_amount double comment '无抵/质押贷款余额' ,
manual_loan_use_limit double comment '贷记卡使用额度' ,
manual_loan_overdue_amount double comment '准贷记卡透支余额' ,
manual_remark string comment '备注' ,
create_user_id string comment '创建人id' ,
update_user_id string comment '更新人id' ,
create_time string comment '记录创建时间' ,
update_time string comment '记录更新时间' ,
credit_num bigint comment '上传数量' ,
credit_modify_time string comment '最后上传时间' ,
credit_operate_user string comment '最后上传征信操作人' ,
business_work_unit string comment '工商工作单位' ,
business_query_time string comment '工商查询时间' ,
business_is_self_employed string comment '工商是否为自雇人士' ,
business_self_employed_type string comment '工商自雇人士类型' ,
business_query_result string comment '工商查询结果' ,
business_query_user_id string comment '工商查询人id' ,
business_query_user_name string comment '工商查询姓名' ,
business_business_remark string comment '工商备注' ,
business_create_user_id string comment '工商创建人id' ,
business_update_user_id string comment '工商更新人id' ,
business_create_time string comment '工商记录创建时间' ,
business_update_time string comment '工商记录更新时间' ,
business_flag string comment '工商请求结果-Y：请求成功；N：请求失败' ,
business_type_json string comment '工商会将查询参数保存在这里'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_order_credit_risks';


create table if not exists dwd.dwd_order_houses(id string comment 'ID' ,
house_api string comment '房产信息类型' ,
house_apply_no string comment '订单编号' ,
house_no string comment '房产编号' ,
house_cert_type string comment '房产证类型' ,
house_cert_no string comment '产证编号' ,
house_new_house_cert_no string comment '新房产证编号' ,
house_type string comment '房产用途' ,
house_area string comment '所在区域' ,
house_address string comment '房产地址（坐落）' ,
house_acreage string comment '房屋面积' ,
house_register_price double comment '登记价（元）' ,
house_register_date string comment '登记日期' ,
house_completion_date string comment '竣工日期' ,
house_land_expiry string comment '土地使用期限' ,
house_land_right_no string comment '丘权号' ,
house_remark string comment '备注' ,
house_property_owner_info string comment '产权人相关信息' ,
house_create_user_id string comment '创建人id' ,
house_update_user_id string comment '更新人id' ,
house_create_time string comment '记录创建时间' ,
house_update_time string comment '记录更新时间' ,
house_age string comment '房龄' ,
house_housing_status string comment '房屋现状(对应字典表fwxz)' ,
house_property string comment '房屋性质' ,
house_type_other string comment '房产用途其他' ,
house_location string comment '房产证地址（省份、直辖市、自治区  （广东省，深圳市，南山区）逗号分隔）' ,
house_location_province string comment '省' ,
house_location_city string comment '市' ,
house_area_code string comment '区域编码' ,
house_interior_house_acreage string comment '套内建筑面积' ,
house_borrower_equity double comment '借款人产权份额' ,
house_owner_type string comment '共有情况' ,
house_owner_number bigint comment '共有产权人数' ,
house_mortgage_date string comment '抵押日期' ,
house_mortgage_struct string comment '抵押物房屋结构' ,
house_mortgage_type string comment '抵押物房屋类型' ,
house_mortgage_status string comment '抵押状态' ,
house_rent_status string comment '出租情况' ,
house_right_property string comment '权利性质' ,
house_right_type string comment '权利类型' ,
house_total_floor bigint comment '总层数' ,
house_prop_buy_time string comment '购房日期' ,
house_project_name string comment '楼盘名称' ,
house_is_only_house string comment '' ,
house_fxt_area_code string comment '房讯通区域编码' ,
house_fxt_area_name string comment '房讯通区域名称' ,
house_village_name string comment '' ,
house_building_no string comment '' ,
house_floor_no string comment '' ,
house_room_no string comment '' ,
house_build_year string comment '' ,
house_land_type string comment '土地类型' ,
house_is_second_mortgage string comment '是否在我司二押' ,
house_mold string comment '房产类型' ,
house_loan_agency_type string comment '贷款机构类型' ,
house_loan_agency_name string comment '贷款机构名称' ,
house_mortgage_right_amount string comment '抵押债权金额' ,
house_other_estate_type string comment '其他房产类型' ,
house_comprehensive_average_price double comment '综合评估均价' ,
house_comprehensive_evaluation_price double comment '综合评估总价' ,
house_in_reserve_house string comment '是否备用房' ,
land_parcel_no string comment '地号（宗地号）' ,
land_useright_gain_way string comment '使用权取得方式' ,
land_use string comment '土地用途' ,
land_remark string comment '备注' ,
land_create_user_id string comment '创建人id' ,
land_update_user_id string comment '更新人id' ,
land_create_time string comment '记录创建时间' ,
land_update_time string comment '记录更新时间' ,
land_useright_gain_way_other string comment '使用权取得方式其他' ,
land_type_other string comment '地类其他' ,
land_type string comment '地类地类地类' ,
land_area_use double comment '使用权面积' ,
land_share_area double comment '分摊面积' ,
land_house_location string comment '房屋坐落' ,
land_end_date string comment '终止日期' ,
land_alone_area double comment '独用面积' ,
estimate_price_source string comment '价格来源' ,
estimate_query_time string comment '查询时间' ,
estimate_market_average_price double comment '市场均价（元）' ,
estimate_query_user_id string comment '查询人id' ,
estimate_query_user_name string comment '查询姓名' ,
estimate_remark string comment '备注' ,
estimate_create_user_id string comment '创建人id' ,
estimate_update_user_id string comment '更新人id' ,
estimate_create_time string comment '记录创建时间' ,
estimate_update_time string comment '记录更新时间' ,
estimate_rev bigint comment '版本号' ,
estimate_sourceType string comment '征信来源' ,
estimate_total_price double comment '查评估总价1' ,
estimate_manual_total_price double comment '人工录入评估总价2' ,
estimate_average_price double comment '查评估均价' ,
estimate_liveness string comment '活跃度' ,
estimate_average_price2 double comment '查评估均价2' ,
estimate_total_price2 double comment '查评估总价2' ,
estimate_comprehensive_evaluation_price double comment '综合评估价' ,
estimate_comprehensive_average_price double comment '综合均价' ,
estimate_total_price3 double comment '云房总价' ,
estimate_average_price3 double comment '云房均价' ,
estimate_old_or_new string comment '新老单标记' ,
estimate_system_source string comment '系统来源' ,
estimate_query_condition string comment '查询条件' ,
estimate_price double comment '均价(元/m2)' ,
estimate_query_way string comment '查询方式(线上/线下)' ,
estimate_query_result string comment '查询结果状态' ,
estimate_unique_id string comment '查询条件' ,
archive_query_time string comment '查询时间' ,
archive_query_result string comment '查档结果' ,
archive_query_user_id string comment '查档人id' ,
archive_query_user_name string comment '查档人姓名' ,
archive_remark string comment '备注' ,
archive_create_user_id string comment '创建人id' ,
archive_update_user_id string comment '更新人id' ,
archive_create_time timestamp comment '记录创建时间' ,
archive_update_time string comment '记录更新时间'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_order_houses';

create table if not exists dwd.dwd_order_insurances(id string comment '主键id' ,
apply_no string comment '订单编号' ,
insurance_no string comment '保单号' ,
insurance_type string comment '保险类型' ,
insurance_name string comment '保险名称' ,
insurer_name string comment '投保人姓名' ,
insurer_cert_id string comment '投保人证件号码' ,
insurer_phone string comment '投保人联系电话' ,
insurer_mail string comment '投保人电子邮件' ,
insurer_adress string comment '投保人联系地址' ,
insured_name string comment '被保险人姓名' ,
insured_cret_id string comment '被保险人证件号码' ,
insured_phone string comment '被保险人联系电话' ,
insured_mail string comment '被保险人电子邮件' ,
premium_amount double comment '保费' ,
insurance_amount double comment '保险金额' ,
payment_way string comment '收费方式' ,
payment_party string comment '保费缴纳方' ,
insurance_period string comment '保险期限/履约期' ,
preliminary_pass_time string comment '预审通过时间' ,
receive_policy_time string comment '接收报单时间' ,
underwrite_pass_time string comment '核保通过时间' ,
premium_payment_time string comment '保费缴纳时间' ,
remark string comment '备注' ,
create_user_id string comment '创建人id' ,
update_user_id string comment '更新人id' ,
create_time string comment '记录创建时间' ,
update_time string comment '记录更新时间' ,
rev bigint comment '版本号' ,
delete_flag string comment '记录删除标识(1：删除；0：有效记录)' ,
is_pass string comment '是否核保通过' ,
robot_status string comment '机器人操作状态(successfailure)'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_order_insurances';


create table if not exists dwd.dwd_order_projects(id string comment '主键id' ,
apply_no string comment '业务申请编号' ,
account_type string comment '资料托管类型  身份证托管：SFZ 银行卡托管：YHK  房地产证：FDCZ  其他要件托管：QT' ,
account_name string comment '类型名' ,
account_no string comment '类型号' ,
card_type string comment '托管银行卡类型供楼卡:GLK  按揭回款卡:AJHKK 首期款回款卡:SQKHKK' ,
bank_code string comment '银行编码' ,
bank_name string comment '银行名称' ,
reback_date string comment '托管证件归还日期' ,
remark string comment '备注' ,
create_user_id string comment '创建人id' ,
update_user_id string comment '更新人id' ,
create_time string comment '记录创建时间' ,
update_time string comment '记录更新时间' ,
is_trust_flag string comment '是否托管' ,
is_close_flag string comment '是否关闭网银' ,
storage_time string comment '入库时间' ,
storage_operator string comment '入库交接人' ,
storage_operator_id string comment '入库交接人id' ,
storage_receiver string comment '入库签收人' ,
storage_receiver_id string comment '入库签收人id' ,
storageout_time string comment '出库时间' ,
storageout_operator string comment '出库交接人' ,
storageout_operator_id string comment '出库交接人id' ,
storageout_receiver string comment '出库签收人' ,
storageout_receiver_id string comment '出库签收人id' ,
usb_key string comment 'U盾，Y 有，N 无' ,
test_account_id string comment '要件测试托管资料主键' ,
test_time string comment '要件测试时间' ,
test_channel string comment '要件测试途径（POS:POS机、DSK:柜台、ATM:自助柜员机、OTE:其它)' ,
test_result string comment '要件测试结果（Y正常；N异常）' ,
test_handle_user_id string comment '要件测试办理人员id' ,
handle_user_name string comment '要件测试办理人员姓名' ,
test_remark string comment '要件测试备注' ,
test_create_user_id string comment '要件测试创建人id' ,
test_update_user_id string comment '要件测试更新人id' ,
test_create_time string comment '要件测试记录创建时间' ,
test_update_time string comment '要件测试记录更新时间'
)
row format delimited fields terminated by '\t'
location '/user/hive/warehouse/dwd_dwd_order_projects';