use ods;
drop table if exists dwd.dwdtmp_update_data_detail;
CREATE TABLE if not exists dwd.dwdtmp_update_data_detail (   id STRING,   apply_no STRING,   flow_instance_id STRING,   update_module STRING,   update_module_name STRING,   field STRING,   field_name STRING,   o_value STRING,   n_value STRING,datau_time timestamp,remark string,other_remark string ) STORED AS parquet;
-- biz_data_update_customer_info
insert overwrite table dwd.dwdtmp_update_data_detail
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' relation' 'field','原关系类型' 'field_name',sduo.o_relation 'o_value',sdun.n_relation 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci
left join (select key_,name_ n_relation from ods_bpms_sys_dic_common where type_id_='10000034210010' or type_id_='10000025010003' or type_id_='10000060121010') sdun on sdun.key_=lower(uci.n_relation)
left join (select key_,name_ o_relation from ods_bpms_sys_dic_common where type_id_='10000034210010' or type_id_='10000025010003' or type_id_='10000060121010') sduo on sduo.key_=lower(uci.o_relation)
where uci.o_relation <>uci.n_relation union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' isProposer' 'field','原是否为申请人' 'field_name',regexp_replace(regexp_replace(uci.o_isProposer,'Y','是'),'N','否') 'o_value',regexp_replace(regexp_replace(uci.n_isProposer,'Y','是'),'N','否') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_isProposer <>uci.n_isProposer union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' isActualBorrowerName' 'field','原是否为主借款人/投保人' 'field_name',regexp_replace(regexp_replace(uci.o_isActualBorrowerName,'Y','是'),'N','否') 'o_value',regexp_replace(regexp_replace(uci.n_isActualBorrowerName,'Y','是'),'N','否') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_isActualBorrowerName <>uci.n_isActualBorrowerName union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' name' 'field','原姓名' 'field_name',uci.o_name 'o_value',uci.n_name 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_name <>uci.n_name union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' id_card_type' 'field','原证件类型' 'field_name',sduo.o_id_card_type 'o_value',sdun.n_id_card_type 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci
left join (select key_,name_ n_id_card_type from ods_bpms_sys_dic_common where type_id_='10000000520012') sdun on sdun.key_=lower(uci.n_id_card_type)
left join (select key_,name_ o_id_card_type from ods_bpms_sys_dic_common where type_id_='10000000520012') sduo on sduo.key_=lower(uci.o_id_card_type)
where uci.o_id_card_type <>uci.n_id_card_type union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' id_card_no' 'field','原证件号码' 'field_name',uci.o_id_card_no 'o_value',uci.n_id_card_no 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_id_card_no <>uci.n_id_card_no union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' phone' 'field','原客户联系方式' 'field_name',uci.o_phone 'o_value',uci.n_phone 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_phone <>uci.n_phone union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' address' 'field','原家庭住址' 'field_name',uci.o_address 'o_value',uci.n_address 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_address <>uci.n_address union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' age' 'field','原年龄' 'field_name',uci.o_age 'o_value',uci.n_age 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_age <>uci.n_age union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' id_card_validity' 'field','原证件有效期' 'field_name',uci.o_id_card_validity 'o_value',uci.n_id_card_validity 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_id_card_validity <>uci.n_id_card_validity union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' marital_status' 'field','原婚姻状态' 'field_name',sduo.o_marital_status 'o_value',sdun.n_marital_status 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci
left join (select key_,name_ n_marital_status from ods_bpms_sys_dic_common where type_id_='10000001220210') sdun on sdun.key_=lower(uci.n_marital_status)
left join (select key_,name_ o_marital_status from ods_bpms_sys_dic_common where type_id_='10000001220210') sduo on sduo.key_=lower(uci.o_marital_status)
where uci.o_marital_status <>uci.n_marital_status union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' education' 'field','原教育程度' 'field_name',sduo.o_education 'o_value',sdun.n_education 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci
left join (select key_,name_ n_education from ods_bpms_sys_dic_common where type_id_='10000004140002') sdun on sdun.key_=uci.n_education
left join (select key_,name_ o_education from ods_bpms_sys_dic_common where type_id_='10000004140002') sduo on sduo.key_=uci.o_education
where uci.o_education <>uci.n_education union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' monthly_income' 'field','原个人月收入' 'field_name',CAST (uci.o_monthly_income AS STRING) 'o_value',CAST(uci.n_monthly_income AS STRING) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_monthly_income <>uci.n_monthly_income union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' income_type' 'field','原收入类型' 'field_name',sduo.o_income_type 'o_value',sdun.n_income_type 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci
left join (select key_,name_ n_income_type from ods_bpms_sys_dic_common where type_id_='10000001220217') sdun on sdun.key_=lower(uci.n_income_type)
left join (select key_,name_ o_income_type from ods_bpms_sys_dic_common where type_id_='10000001220217') sduo on sduo.key_=lower(uci.o_income_type)
where uci.o_income_type <>uci.n_income_type union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' has_children' 'field','原有无子女' 'field_name',regexp_replace(regexp_replace(uci.o_has_children,'Y','是'),'N','否') 'o_value',regexp_replace(regexp_replace(uci.n_has_children,'Y','是'),'N','否') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_has_children <>uci.n_has_children union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' employer' 'field','原工作单位' 'field_name',uci.o_employer 'o_value',uci.n_employer 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_employer <>uci.n_employer union all
select uci.id,uci.apply_no,uci.flow_instance_id,'customerInfo' 'update_module','客户信息' 'update_module_name',' email' 'field','原电子邮箱' 'field_name',uci.o_email 'o_value',uci.n_email 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_customer_info uci where uci.o_email <>uci.n_email union  all
select uci.id,uci.apply_no,uci.flow_instance_id,'accountinfo' 'update_module','账户信息' 'update_module_name','is_platform_return_account' 'field','原是否选定为平台款还款账户' 'field_name',regexp_replace(regexp_replace(uci.o_is_platform_return_account,'Y','是'),'N','否') 'o_value',regexp_replace(regexp_replace(uci.n_is_platform_return_account,'Y','是'),'N','否') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_account_info uci where uci.o_is_platform_return_account <>uci.n_is_platform_return_account union all
select uci.id,uci.apply_no,uci.flow_instance_id,'accountinfo' 'update_module','账户信息' 'update_module_name','type' 'field','原账户类型' 'field_name',sduo.o_type 'o_value',sdun.n_type 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_account_info uci
left join (select key_,name_ n_type from ods_bpms_sys_dic_common where type_id_='10000000142889' ) sdun on sdun.key_=lower(uci.n_type)
left join (select key_,name_ o_type from ods_bpms_sys_dic_common where type_id_='10000000142889' ) sduo on sduo.key_=lower(uci.o_type)
where uci.o_type <>uci.n_type union all
select uci.id,uci.apply_no,uci.flow_instance_id,'accountinfo' 'update_module','账户信息' 'update_module_name','name' 'field','原户名' 'field_name',uci.o_name 'o_value',uci.n_name 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_account_info uci where uci.o_name <>uci.n_name union all
select uci.id,uci.apply_no,uci.flow_instance_id,'accountinfo' 'update_module','账户信息' 'update_module_name','number' 'field','原账户号' 'field_name',uci.o_number 'o_value',uci.n_number 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_account_info uci where uci.o_number <>uci.n_number union all
select uci.id,uci.apply_no,uci.flow_instance_id,'accountinfo' 'update_module','账户信息' 'update_module_name','open_bank' 'field','原开户行' 'field_name',uci.o_open_bank 'o_value',uci.n_open_bank 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_account_info uci where uci.o_open_bank <>uci.n_open_bank union all

-- biz_data_update_deal_info
select uci.id,uci.apply_no,uci.flow_instance_id,'dealinfo' 'update_module','交易信息' 'update_module_name','trading_price' 'field','原合同成交价' 'field_name',cast (uci.o_trading_price as string) 'o_value',cast (uci.n_trading_price as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_deal_info uci where uci.o_trading_price <>uci.n_trading_price union all
select uci.id,uci.apply_no,uci.flow_instance_id,'dealinfo' 'update_module','交易信息' 'update_module_name','actual_trading_price' 'field','原实际成交价' 'field_name',cast (uci.o_actual_trading_price as string) 'o_value'  ,cast(uci.n_actual_trading_price as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_deal_info uci where uci.o_actual_trading_price <>uci.n_actual_trading_price union all
-- biz_data_update_fee_info
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','borrowingValueDate' 'field','原借款起息日（客户）' 'field_name',uci.o_borrowingValueDate 'o_value',uci.n_borrowingValueDate 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_borrowingValueDate <>uci.n_borrowingValueDate union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','borrowingDueDate' 'field','原实际借款回款日（客户）-新增字段' 'field_name',uci.o_borrowingDueDate 'o_value',uci.n_borrowingDueDate 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_borrowingDueDate <>uci.n_borrowingDueDate union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','countHeadTail' 'field','原算头算尾方式-新增字段' 'field_name',sduo.o_countHeadTail 'o_value',sdun.n_countHeadTail 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci
left join (select key_,name_ n_countHeadTail from ods_bpms_sys_dic_common where type_id_='10000104170215' ) sdun on sdun.key_=lower(uci.n_countHeadTail)
left join (select key_,name_ o_countHeadTail from ods_bpms_sys_dic_common where type_id_='10000104170215' ) sduo on sduo.key_=lower(uci.o_countHeadTail)
where uci.o_countHeadTail <>uci.n_countHeadTail union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','platformValueDate' 'field','原平台起息日：' 'field_name',uci.o_platformValueDate 'o_value',uci.n_platformValueDate 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_platformValueDate <>uci.n_platformValueDate union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','productTermAndChargeWay' 'field','原收费方式选择' 'field_name',sduo.o_productTermAndChargeWay 'o_value',sdun.n_productTermAndChargeWay 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci
left join (select key_,name_ n_productTermAndChargeWay from ods_bpms_sys_dic_common where type_id_='10000045260203' ) sdun on sdun.key_=lower(uci.n_productTermAndChargeWay)
left join (select key_,name_ o_productTermAndChargeWay from ods_bpms_sys_dic_common where type_id_='10000045260203' ) sduo on sduo.key_=lower(uci.o_productTermAndChargeWay)

where uci.o_productTermAndChargeWay <>uci.n_productTermAndChargeWay union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','hasBillFlag' 'field','原是否有专票' 'field_name',regexp_replace(regexp_replace(uci.o_hasBillFlag,'Y','是'),'N','否')'o_value',regexp_replace(regexp_replace(uci.n_hasBillFlag,'Y','是'),'N','否') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_hasBillFlag <>uci.n_hasBillFlag union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','tag' 'field','原渠道标签（加盟商不显示）' 'field_name',sduo.o_tag 'o_value',sdun.n_tag 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci
left join (select key_,name_ n_tag from ods_bpms_sys_dic_common where type_id_='10000039870069' ) sdun on sdun.key_=lower(uci.n_tag)
left join (select key_,name_ o_tag from ods_bpms_sys_dic_common where type_id_='10000039870069' ) sduo on sduo.key_=lower(uci.o_tag)
where uci.o_tag <>uci.n_tag union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','channelName' 'field','原渠道名称（加盟商不显示）' 'field_name',uci.o_channelName 'o_value',uci.n_channelName 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_channelName <>uci.n_channelName union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','priceTag' 'field','原价格标签（加盟商不显示，自营显示不可修改）' 'field_name',sduo.o_priceTag 'o_value',sdun.n_priceTag 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci
left join (select key_,name_ n_priceTag from ods_bpms_sys_dic_common where type_id_='10000042640043' ) sdun on sdun.key_=lower(uci.n_priceTag)
left join (select key_,name_ o_priceTag from ods_bpms_sys_dic_common where type_id_='10000042640043' ) sduo on sduo.key_=lower(uci.o_priceTag)
where uci.o_priceTag <>uci.n_priceTag union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','priceDiscount' 'field','原定价折扣（加盟商不显示，自营显示不可修改）' 'field_name',uci.o_priceDiscount 'o_value',uci.n_priceDiscount 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_priceDiscount <>uci.n_priceDiscount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','riskLevel' 'field','原风险等级' 'field_name',sduo.o_riskLevel 'o_value',sdun.n_riskLevel 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci
left join (select key_,name_ n_riskLevel from ods_bpms_sys_dic_common where type_id_='10000042260011' ) sdun on sdun.key_=lower(uci.n_riskLevel)
left join (select key_,name_ o_riskLevel from ods_bpms_sys_dic_common where type_id_='10000042260011' ) sduo on sduo.key_=lower(uci.o_riskLevel)
where uci.o_riskLevel <>uci.n_riskLevel union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','channelPricePerOrder' 'field','原渠道价%/笔（%）' 'field_name',cast (uci.o_channelPricePerOrder as string) 'o_value',cast (uci.n_channelPricePerOrder as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_channelPricePerOrder <>uci.n_channelPricePerOrder union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','agentCommissionPerOrder' 'field','原代收返佣%/笔（%）' 'field_name',cast(uci.o_agentCommissionPerOrder as string) 'o_value',cast (uci.n_agentCommissionPerOrder  as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_agentCommissionPerOrder <>uci.n_agentCommissionPerOrder union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','overdueRatePerDay' 'field','原超期费率%/天（%）' 'field_name',cast (uci.o_overdueRatePerDay as string) 'o_value',cast (uci.n_overdueRatePerDay  as string)  'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_overdueRatePerDay <>uci.n_overdueRatePerDay union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','channelPricePerOrderFirstPart' 'field','原首段期限渠道价/笔(%)' 'field_name',cast(uci.o_channelPricePerOrderFirstPart as string)  'o_value',cast(uci.n_channelPricePerOrderFirstPart as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_channelPricePerOrderFirstPart <>uci.n_channelPricePerOrderFirstPart union all
select uci.id,uci.apply_no,uci.flow_instance_id,'feeinfo' 'update_module','费率信息' 'update_module_name','channelPricePerOrderPerPart' 'field','原其他时间段渠道价/段(%)' 'field_name',cast (uci.o_channelPricePerOrderPerPart as string) 'o_value',cast(uci.n_channelPricePerOrderPerPart as string)  'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_fee_info uci where uci.o_channelPricePerOrderPerPart <>uci.n_channelPricePerOrderPerPart union all
-- biz_data_update_house_info
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','house_area' 'field','原房产所在区域' 'field_name',uci.o_house_area 'o_value',uci.n_house_area 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci where uci.o_house_area <>uci.n_house_area union all
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','house_acreage' 'field','原房屋面积（㎡）' 'field_name',cast (uci.o_house_acreage as string) 'o_value',cast(uci.n_house_acreage  as string)'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci where uci.o_house_acreage <>uci.n_house_acreage union all
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','house_address' 'field','原房产地址（坐落）' 'field_name',uci.o_house_address 'o_value',uci.n_house_address 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci where uci.o_house_address <>uci.n_house_address union all
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','house_type' 'field','原房产用途' 'field_name',sduo.o_house_type 'o_value',sdun.n_house_type 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci
left join (select key_,name_ n_house_type from ods_bpms_sys_dic_common where type_id_='10000028440005' ) sdun on sdun.key_=lower(uci.n_house_type)
left join (select key_,name_ o_house_type from ods_bpms_sys_dic_common where type_id_='10000028440005' ) sduo on sduo.key_=lower(uci.o_house_type)
where uci.o_house_type <>uci.n_house_type union all
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','property_owner_info' 'field','原产权人信息' 'field_name',regexp_replace(regexp_replace(regexp_replace(regexp_replace(uci.o_property_owner_info,'PERSONAL','个人'),'PUBLIC','公司'),'\\[',''),'\\]','') 'o_value',regexp_replace(regexp_replace(regexp_replace(regexp_replace(uci.n_property_owner_info,'PERSONAL','个人'),'PUBLIC','公司'),'\\[',''),'\\]','') 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci where uci.o_property_owner_info <>uci.n_property_owner_info union all
select uci.id,uci.apply_no,uci.flow_instance_id,'houseinfo' 'update_module','房产信息' 'update_module_name','cert_type' 'field','原房产证类型' 'field_name',sduo.o_cert_type 'o_value',sdun.n_cert_type 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_house_info uci
left join (select key_,name_ n_cert_type from ods_bpms_sys_dic_common where type_id_='10000051150512' ) sdun on sdun.key_=lower(uci.n_cert_type)
left join (select key_,name_ o_cert_type from ods_bpms_sys_dic_common where type_id_='10000051150512' ) sduo on sduo.key_=lower(uci.o_cert_type)
where uci.o_cert_type <>uci.n_cert_type union all
-- biz_data_update_new_loan_info
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','new_loan_bank_name' 'field','原新贷款银行' 'field_name',uci.o_new_loan_bank_name 'o_value',uci.n_new_loan_bank_name 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci where uci.o_new_loan_bank_name <>uci.n_new_loan_bank_name union all
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','biz_loan_amount' 'field','原实际商业贷款金额（元）' 'field_name',cast (uci.o_biz_loan_amount as string) 'o_value',cast(uci.n_biz_loan_amount  as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci where uci.o_biz_loan_amount <>uci.n_biz_loan_amount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','new_loan_rate' 'field','原贷款利率（%）' 'field_name',cast(uci.o_new_loan_rate  as string) 'o_value',cast(uci.n_new_loan_rate  as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci where uci.o_new_loan_rate <>uci.n_new_loan_rate union all
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','loan_terms' 'field','原贷款期数（月）' 'field_name',cast(uci.o_loan_terms  as string) 'o_value',cast(uci.n_loan_terms   as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci where uci.o_loan_terms <>uci.n_loan_terms union all
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','repay_method_loan' 'field','原还款方式' 'field_name',sduo.o_repay_method_loan 'o_value',sdun.n_repay_method_loan 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci
left join (select key_,name_ n_repay_method_loan from ods_bpms_sys_dic_common where type_id_='10000051150955' ) sdun on sdun.key_=lower(uci.n_repay_method_loan)
left join (select key_,name_ o_repay_method_loan from ods_bpms_sys_dic_common where type_id_='10000051150955' ) sduo on sduo.key_=lower(uci.o_repay_method_loan)
where uci.o_repay_method_loan <>uci.n_repay_method_loan
union all
select uci.id,uci.apply_no,uci.flow_instance_id,'newloaninfo' 'update_module','新贷款信息' 'update_module_name','borrow_cont_no' 'field','原借款合同编号' 'field_name',uci.o_borrow_cont_no 'o_value',uci.n_borrow_cont_no 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_new_loan_info uci where uci.o_borrow_cont_no <>uci.n_borrow_cont_no union all
-- biz_data_update_ori_loan_info
select uci.id,uci.apply_no,uci.flow_instance_id,'oriloaninfo' 'update_module','原贷款信息' 'update_module_name','ori_loan_bank_name' 'field','原原贷款机构' 'field_name',uci.o_ori_loan_bank_name 'o_value',uci.n_ori_loan_bank_name 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_ori_loan_info uci where uci.o_ori_loan_bank_name <>uci.n_ori_loan_bank_name union all
select uci.id,uci.apply_no,uci.flow_instance_id,'oriloaninfo' 'update_module','原贷款信息' 'update_module_name','busi_deduct_principal_balance' 'field','原商贷本金余额（元）' 'field_name',cast (uci.o_busi_deduct_principal_balance as string) 'o_value',cast(uci.n_busi_deduct_principal_balance as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_ori_loan_info uci where uci.o_busi_deduct_principal_balance <>uci.n_busi_deduct_principal_balance union all
-- biz_data_update_other_info
select uci.id,uci.apply_no,uci.flow_instance_id,'otherinfo' 'update_module','其它信息' 'update_module_name','ransomCutTime' 'field','原赎楼扣款时间' 'field_name',cast (uci.o_ransomCutTime as string) 'o_value',cast(uci.n_ransomCutTime as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_other_info uci where uci.o_ransomCutTime <>uci.n_ransomCutTime union all
select uci.id,uci.apply_no,uci.flow_instance_id,'otherinfo' 'update_module','其它信息' 'update_module_name','ransomCutAmount' 'field','原赎楼扣款金额' 'field_name',cast (uci.o_ransomCutAmount as string) 'o_value',cast (uci.n_ransomCutAmount as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_other_info uci where uci.o_ransomCutAmount <>uci.n_ransomCutAmount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'otherinfo' 'update_module','其它信息' 'update_module_name','ruleType' 'field','原订单关联类型' 'field_name',sduo.o_ruleType 'o_value',sdun.n_ruleType 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_other_info uci
left join (select key_,name_ n_ruleType from ods_bpms_sys_dic_common where type_id_='10000080670030' ) sdun on sdun.key_=lower(uci.n_ruleType)
left join (select key_,name_ o_ruleType from ods_bpms_sys_dic_common where type_id_='10000080670030' ) sduo on sduo.key_=lower(uci.o_ruleType)
where uci.o_ruleType <>uci.n_ruleType union all
select uci.id,uci.apply_no,uci.flow_instance_id,'otherinfo' 'update_module','其它信息' 'update_module_name','subRuleType' 'field','原二级类型' 'field_name',uci.o_subRuleType 'o_value',uci.n_subRuleType 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_other_info uci

where uci.o_subRuleType <>uci.n_subRuleType union all
-- biz_data_update_product_info
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','tailReleaseNode' 'field','原放款节点 ' 'field_name',sduo.o_tailReleaseNode 'o_value',sdun.n_tailReleaseNode 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci
left join (select key_,name_ n_tailReleaseNode from ods_bpms_sys_dic_common where type_id_='10000047750219' ) sdun on sdun.key_=lower(uci.n_tailReleaseNode)
left join (select key_,name_ o_tailReleaseNode from ods_bpms_sys_dic_common where type_id_='10000047750219' ) sduo on sduo.key_=lower(uci.o_tailReleaseNode)
where uci.o_tailReleaseNode <>uci.n_tailReleaseNode union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','partnerInsuranceName' 'field','原合作机构' 'field_name',uci.o_partnerInsuranceName 'o_value',uci.n_partnerInsuranceName 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_partnerInsuranceName <>uci.n_partnerInsuranceName union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','refundSource' 'field','原回款来源' 'field_name',sduo.o_refundSource 'o_value',sdun.n_refundSource 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci
left join (select key_,name_ n_refundSource from ods_bpms_sys_dic_common where type_id_='10000032530229' ) sdun on sdun.key_=lower(uci.n_refundSource)
left join (select key_,name_ o_refundSource from ods_bpms_sys_dic_common where type_id_='10000032530229' ) sduo on sduo.key_=lower(uci.o_refundSource)
where uci.o_refundSource <>uci.n_refundSource union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','borrowTerm' 'field','原借款期限' 'field_name',cast (uci.o_borrowTerm as string) 'o_value',cast (uci.n_borrowTerm as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_borrowTerm <>uci.n_borrowTerm union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','borrowingAmount' 'field','原借款金额（元）' 'field_name',cast (uci.o_borrowingAmount as string) 'o_value',cast(uci.n_borrowingAmount as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_borrowingAmount <>uci.n_borrowingAmount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','expectCost' 'field','原预估用款期限' 'field_name',cast (uci.o_expectCost as string)'o_value',cast (uci.n_expectCost as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_expectCost <>uci.n_expectCost union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','ownFundAmount' 'field','原卖方自有资金（元）' 'field_name',cast(uci.o_ownFundAmount as string) 'o_value',cast(uci.n_ownFundAmount as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_ownFundAmount <>uci.n_ownFundAmount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','partnerBankName' 'field','原合作银行' 'field_name',uci.o_partnerBankName 'o_value',uci.n_partnerBankName 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_partnerBankName <>uci.n_partnerBankName union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','productTerm' 'field','原产品期限' 'field_name',cast (uci.o_productTerm as string) 'o_value',cast (uci.n_productTerm as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_productTerm <>uci.n_productTerm union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','ransomBorrowAmount' 'field','原赎楼金额（元）' 'field_name',cast (uci.o_ransomBorrowAmount as string) 'o_value',cast (uci.n_ransomBorrowAmount as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_ransomBorrowAmount <>uci.n_ransomBorrowAmount union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','mostPermission' 'field','原（申请）保险金额' 'field_name',cast (uci.o_mostPermission as string) 'o_value',cast (uci.n_mostPermission as string) 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci where uci.o_mostPermission <>uci.n_mostPermission union all
select uci.id,uci.apply_no,uci.flow_instance_id,'productinfo' 'update_module','产品信息' 'update_module_name','tailAccountType' 'field','原尾款收款账户类型' 'field_name',sduo.o_tailAccountType 'o_value',sdun.n_tailAccountType 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_product_info uci
left join (select key_,name_ n_tailAccountType from ods_bpms_sys_dic_common where type_id_='10000000142889' ) sdun on sdun.key_=lower(uci.n_tailAccountType)
left join (select key_,name_ o_tailAccountType from ods_bpms_sys_dic_common where type_id_='10000000142889' ) sduo on sduo.key_=lower(uci.o_tailAccountType)
where uci.o_tailAccountType <>uci.n_tailAccountType union all
-- biz_data_update_sales_info
select uci.id,uci.apply_no,uci.flow_instance_id,'sales_user_info' 'update_module','渠道经理模块' 'update_module_name','salesUserName' 'field','原修改渠道经理' 'field_name',uci.o_salesUserName 'o_value',uci.n_salesUserName 'n_value', uci.datau_time,uci.remark,uci.otherremark from ods_bpms_biz_data_update_sales_info uci where uci.o_salesUserName <>uci.n_salesUserName;